### ISSUE TITLE
In Sample Camera App setting list items are overlapped with radios

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#101]
![image](https://user-images.githubusercontent.com/2246331/57767672-3db28a00-770a-11e9-9820-1967199ca4b0.png)
Reproduction steps:
1. Tizen SDK --> Sample --> Camera app
2. update TAU to latest one
3. Run Camera app go to settings --> Picture size

**Comment by pkaczmarczy** [comment]
Application was modifying position and display properties of elements inside list.
Change in application source has been proposed.
