### ISSUE TITLE
[mobile] Wrong buttons width for 673x411

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1016]
Wrong buttons width for 673x411
Guide see p. 73
Feedback p. 14
Contained buttons -> Body_area

**Comment by lslachciak** [comment]
in reference to guideline we need also 
    define default width to 60%
    define min width to 240
    update example (min width button)

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged.

**Comment by lslachciak** [comment]
wokrs fine
