### ISSUE TITLE
Buttons -> Contained button ->Body Area -> 2 Buttons: no 24 px margin

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1017]
Buttons -> Contained button ->Body Area -> 2 Buttons: no 24 px margin
Feedback p. 15
Guide p. 74

**Comment by TomaszLukawskiSam** [comment]
@lslachciak  
I think that issue has already been resolved by patch to another issue PR https://github.com/Samsung/TAU/pull/1032

**Comment by lslachciak** [comment]
exactly
