### ISSUE TITLE
[mobile] dropdown list

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU#1022]
In case of scren width is over 673, Please adjust so that dropdown list does not appear outside the list area.

![Listdropdown](https://user-images.githubusercontent.com/31196177/80337133-1e1d5e80-8894-11ea-9bce-358bd16c9e90.png)

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged.

**Comment by lslachciak** [comment]
I can't see issue anymore
