### ISSUE TITLE
Title on extended bar is not centered. 

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1026]
Title on extended bar is not centered. Recommended to add 24 px margin so title will be centered
GUI feedback p. 4, 5

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
Do you have some screenshot. What orientation of the center you have on mind, horizontal or vertical?

**Comment by TomaszLukawskiSam** [comment]
AppBar has much more issues with height and margin. The guideline describes different appbar height depends to screen resolution.

**Comment by TomaszLukawskiSam** [comment]
Patch has been merged.

**Comment by lslachciak** [comment]
fine
