### ISSUE TITLE
Title text margin not applied

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1027]
Title text margin not applied
GUI feedback p. 6

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
Do you have some screenshot? Is this issue of AppBar title?

**Comment by lslachciak** [comment]
@TomaszLukawskiSam please check page 6 in [Webapp]SR_GUI_Feedback_200413.pptx

**Comment by TomaszLukawskiSam** [comment]
> @TomaszLukawskiSam please check page 6 in [Webapp]SR_GUI_Feedback_200413.pptx

The issue is resolved by PR #1061

**Comment by TomaszLukawskiSam** [comment]
Patch has been merged.

**Comment by lslachciak** [comment]
ok
