### ISSUE TITLE
Disabled on/off switch has rendering issue

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1034]
![image](https://user-images.githubusercontent.com/2246331/80477355-17522280-894c-11ea-8221-32e359f80562.png)

Circle is not positioned correctly

**Comment by lslachciak** [comment]
Regardless of This PR I think we need to position circle correctly too
, but it is not much visible for enabled one

![image](https://user-images.githubusercontent.com/2246331/80478883-7add4f80-894e-11ea-8dc3-0c1ded325ad7.png)

**Comment by lslachciak** [comment]
![image](https://user-images.githubusercontent.com/2246331/80478855-70bb5100-894e-11ea-9f9f-16003517c241.png)

**Comment by lslachciak** [comment]
Summing up this issue has two PRs:
Fix removing disabled examples: https://github.com/Samsung/TAU/pull/1035
Fix for rendering issue: https://github.com/Samsung/TAU/pull/1038/

**Comment by lslachciak** [comment]
Both PRs merged
