### ISSUE TITLE
TAU version in Etc

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1040]
It would be nice to have displayed TAU version in Exemplary UIComponents app
This will allow testers to easily verify TAU version.

**Comment by HunseopJeong** [comment]
@lslachciak, How about printing the version when executing the script.
I uploaded the PR for this #1148

**Comment by lslachciak** [comment]
@HunseopJeong I think you PR is useful but we will need additional functionality in UIComponents too.
Testers don't have access to UIComponents console, they just install app.
In such case sometimes it is hard to verify easily which TAU version they use.

**Comment by HunseopJeong** [comment]
@lslachciak,
I understood your thoughts.
It would be good to show the version on the UIComponents.
Let's find a way.

**Comment by TomaszLukawskiSam** [comment]
In my opinion the TAU version should be placed in "etc" .

**Comment by HunseopJeong** [comment]
@TomaszLukawskiSam,
Good approach.
@lslachciak, How about your opinion?

**Comment by lslachciak** [comment]
yes, this should be in Etc submenu

**Comment by HunseopJeong** [comment]
Done for the mobile profile

**Comment by TomaszLukawskiSam** [comment]
The patch has already been merged.
