### ISSUE TITLE
[wearable] Presentation View -> List -> Swipe to delete

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1059]
[wearable] Presentation View -> List -> Swipe to delete

**Comment by grzegorz-czajkowski** [comment]
The initial implementation is merged. The follow ups are here  #1227, #1228, #1229, #1230, #1231, #1234.

**Comment by lslachciak** [comment]
works fine
I think most important issues are
https://github.com/Samsung/TAU/issues/1229
https://github.com/Samsung/TAU/issues/1230
https://github.com/Samsung/TAU/issues/1234
