### ISSUE TITLE
Dialogs --> Date & time picker (12h)

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1074]
Please refer to:
GUI Guide p. 138 (v.1.9)
Components UI p. v.17 rel. 2 (p. 94-100)
Reference_SR_200306 (p. 3-6)

**Comment by singa2000** [comment]
F.Y.I.
The Date&Time Picker can use both with dialog and component itself used with body.

In case of Reference app, it use by component itself used with body.

**Comment by lslachciak** [comment]
Right. at this moment the most important is usage in body.
I updated issue description with appropriate reference

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
I think the issue can be close.

**Comment by lslachciak** [comment]
works fine, although two issues exist
https://github.com/Samsung/TAU/issues/1104
https://github.com/Samsung/TAU/issues/1108
