### ISSUE TITLE
Day of week picker in sample app

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1075]
For details see
Reference_SR_200306 - p.6
WebApp_Reference_200313 - p.53-56

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 

Proposed API:
widget name: DayOfWeekPicker
widget HTML markup `<div class="ui-day-of-week-picker" data-value="3,4,5">`
methods:
 - `value([<string>])` - common method for get/set value, argument as string represents number of selected days, 0 - Sunday
   eg. `value('0,1,6')`
         `value()` returns array of days of week eg. [3,4,5] , 0 - is Sunday the same as in Date() class 

events:
 - `dayofweekchange` - event is triggering on widget value change

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged. The issue can be close.

**Comment by lslachciak** [comment]
works fine
