### ISSUE TITLE
Sample App --> Add schedule dialog

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1078]
Implement Add Schedule dialog

For details see
Reference_SR_200306 - p.6
WebApp_Reference_200313 - p.53-56

If some component is missing create issue for this

**Comment by korneliakobiela** [comment]
I drafted today PR. It needs one more action - make it Tizen Studio style project. I am doing it tomorrow.

**Comment by korneliakobiela** [comment]
Schedule dialog was merged - please review.

**Comment by lslachciak** [comment]
Add schedule dialog was added to application. Thank you.
