### ISSUE TITLE
[mobile] [issue] Extending Appbar cause list area to diminish

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1086]
Steps:
1. open example
http://localhost:8080/examples/mobile/SchedulingApp/create-event.html
2. extend appbar
3. collapse appbar
4. extend appbar
5. collapse appbar
Observe:
![image](https://user-images.githubusercontent.com/2246331/81698845-d6d3c800-9466-11ea-9e1b-c2b36dd04698.png)

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
We can join issue with https://github.com/Samsung/TAU/issues/1097 .
I am in the process of solving the problem #1097

**Comment by TomaszLukawskiSam** [comment]
The issue is solving by patch for another issue (https://github.com/Samsung/TAU/pull/1098)

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged. The issue can be close.

**Comment by lslachciak** [comment]
thank you @TomaszLukawskiSam issue no longer exist now.
