### ISSUE TITLE
[wearable] UICOmponents sample app not working

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1094]
repro:
git clean -dfx
npm install

run UIComponents app
observe:
not able to access submenus

**Comment by lslachciak** [comment]
this is critical TAU issue reproducible after running git clean -dfx

**Comment by TomaszLukawskiSam** [comment]
I think that issue is resolved now.

**Comment by lslachciak** [comment]
I can confirm. Issue is fixed now
