### ISSUE TITLE
List divider bottom round corner

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#1097]
The bottom of list is not rounded when it's scrolling.

![obraz](https://user-images.githubusercontent.com/29534410/82039030-abd6b780-96a4-11ea-8f65-22858173772c.png)

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged. The issue can be close.

**Comment by lslachciak** [comment]
verified, works fine
