### ISSUE TITLE
[ScheduleApp] Dark theme colors

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1112]
Verify dark theme colors for sample app
Dark theme color for inactive dates in datetime indicator seems to be wrong
In WebApp_ReferenceXXX.pdf p. 1 it is described as #FDFDFD but currently is #999999

**Comment by lslachciak** [comment]
i send e-mail to UX team to clarify dark theme color. waiting for reply

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
Another point is also shown here. How should the developer define or define colors for themes.
He should define it similar like us but in `style.css`.
```
.ui-theme-light {
    --custom-button: #0381fe;
}
.ui-theme-dark {
    --custom-button: #dddfff;
}
```

**Comment by lslachciak** [comment]
Yes this is important thing to consider. We need to provide mechanism to support such thing

**Comment by lslachciak** [comment]
For Tomasz comment I created separate issue
https://github.com/Samsung/TAU/issues/1173
