### ISSUE TITLE
Button back doesn't work if page has been opened from dialog

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#1118]
![image](https://user-images.githubusercontent.com/29534410/82547185-9a385880-9b59-11ea-9d67-ea50402f8112.png)

Should the opening of the dialogue not be stored in history?

**Comment by lslachciak** [comment]
It should be stored I think

**Comment by lslachciak** [comment]
I think this was fixed by https://github.com/Samsung/TAU/pull/1192

**Comment by TomaszLukawskiSam** [comment]
> I think this was fixed by #1192

The issue still exists but describe the same issue as #1190
