### ISSUE TITLE
Button with "ui-btn" should looks the same as Anchor with "ui-btn"

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#1124]
![image](https://user-images.githubusercontent.com/29534410/82554304-f4d7b180-9b65-11ea-9b23-6d71f0d054d5.png)

![image](https://user-images.githubusercontent.com/29534410/82554396-1e90d880-9b66-11ea-85cb-b0b7549a6469.png)

**Comment by lslachciak** [comment]
is this really ScheduleApp isue? can we treat as TAU issue?

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged
