### ISSUE TITLE
ScheduleApp: Add more menu with theme selection

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#1131]
![obraz](https://user-images.githubusercontent.com/29534410/82661755-dee0f400-9c2c-11ea-83f2-12806af4c6ad.png)

![obraz](https://user-images.githubusercontent.com/29534410/82661911-3a12e680-9c2d-11ea-8298-a2fee2f997d8.png)

**Comment by lslachciak** [comment]
@korneliakobiela user should be able to select theme after clicking three dots

**Comment by korneliakobiela** [comment]
PR Merged - please review

**Comment by TomaszLukawskiSam** [comment]
The issue has been resolved.
