### ISSUE TITLE
Improve performance of date&time picker

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1139]
Scrolling performance should be better. In comparison to native wheel is rotating very slowly.

**Comment by TomaszLukawskiSam** [comment]
Proposition of improvement:
 - change behaviour for drag event - widget should be responsive from drag start
 - increase momentum effect
 - implementation of carousel to widget for reduce number of animated items

**Comment by TomaszLukawskiSam** [comment]
I think we can close the issue.
