### ISSUE TITLE
[mobile] [ScheduleApp] Add schedule dialog in dark theme

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1143]
[mobile] [ScheduleApp] Add schedule dialog in dark theme looks wrong
![Screenshot from 2020-05-27 10-16-15](https://user-images.githubusercontent.com/2246331/82994942-36071000-a003-11ea-8898-63446abe0f6c.png)

**Comment by korneliakobiela** [comment]
PR merged, please review.

**Comment by lslachciak** [comment]
works well, thank you
