### ISSUE TITLE
[ScheduleApp] Clicking Add schedule has no effect

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1144]
1. Schedule
2. Add schedule
3. Turn device On
5. Done
6. Add schedule
Observe:
No reaction in app

**Comment by lslachciak** [comment]
Also there is no change theme option on this screen.
We need to resolve https://github.com/Samsung/TAU/issues/1121or fix this issue

**Comment by lslachciak** [comment]
Issue was fixed by https://github.com/Samsung/TAU/issues/1121
