### ISSUE TITLE
[UIComponents] [ScheduleApp] Status bar color should change according to the theme

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1155]
See WebApp review p.2

![image](https://user-images.githubusercontent.com/2246331/83522964-b3d68a00-a4e1-11ea-8ef5-986c78f017f7.png)

![image](https://user-images.githubusercontent.com/2246331/83522992-bb962e80-a4e1-11ea-98dd-9284ebe8bf08.png)

**Comment by lslachciak** [comment]
We discussed that his is out of TAU app scope
