### ISSUE TITLE
Spin / DateTimePicker: stop scroll on swipe - lack of "dragend" event (sometimes)

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#1168]
The issue cause wrong look of widget:
![obraz](https://user-images.githubusercontent.com/29534410/83730890-003cd980-a64a-11ea-82af-9b6ec98dc6fb.png)

Reproduction path:
- open widget
- try to do fast scroll when finger going out from widget container

**Comment by lslachciak** [comment]
I confirm that issue exists

**Comment by TomaszLukawskiSam** [comment]
I think the issue can be close.

**Comment by lslachciak** [comment]
It is better now, but I still can always reproduce this issue both on desktop as well as on mobile in case of long swipe.
Reproduction:
Start swipe in device On Section
Finish swipe in Device off section below or on the active date
![image](https://user-images.githubusercontent.com/2246331/84652789-7d9b0080-af0c-11ea-86a1-9bb5b6a3dfe0.png)

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
How you think, can we close the issue?

**Comment by lslachciak** [comment]
yes, now issue can be closed. Thank you for patience
