### ISSUE TITLE
(wearable) VirtualList marquee animation is not starting

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU#117]
Marquee animation does not start if item text is loo long.
Text is just cut off by the screen.

Reproduction:
UIComponents app: contents/list/virtual/1_line_btn.html

**Comment by TomaszLukawskiSam** [comment]
I verified the issue on latest version of TAU. The issue was solved by patch for another issue.
https://samsung.github.io/TAU/examples/1.0/examples/wearable/UIComponents/contents/list/virtual/1line_btn.html

**Comment by lslachciak** [comment]
Works good
