### ISSUE TITLE
Links to TAU example apps not working

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1177]
In README on https://github.com/Samsung/TAU/

it is written
Demo application is available on https://samsung.github.io/TAU:

    https://code.tizen.org/TAU/1.2/examples/mobile/UIComponents/ (Mobile)
    https://code.tizen.org/TAU/1.2/examples/wearable/UIComponents/ (Wearable)

Links are not working

**Comment by grzegorz-czajkowski** [comment]
WATT release https://github.com/Samsung/WATT/releases/tag/0.8.5

**Comment by grzegorz-czajkowski** [comment]
Docker image can not be build because of dead links to Tizen Studio - https://github.com/Samsung/WATT/pull/225

WATT release https://github.com/Samsung/WATT/releases/tag/0.8.6

**Comment by grzegorz-czajkowski** [comment]
Both instances are updated. Links are working.

**Comment by lslachciak** [comment]
I confirm
