### ISSUE TITLE
List: Image removed but still exists in implementation - expander

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#1183]
Images have been removed according to GUI guide 2.2 but still exists in implementation
```
tw_expander_close_mtrl_alpha_dark.9.png
tw_expander_close_mtrl_alpha_light.9.png
```

**Comment by lslachciak** [comment]
I would like to leave it on future milestone

**Comment by TomaszLukawskiSam** [comment]
Associations to these images can be safely removed. Verified.

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged.
