### ISSUE TITLE
Need to add the back button for the submenu

### ISSUE THREAD

**Issue by HunseopJeong** [Samsung/TAU#1188]
Some pages have the back button but some do not have..
I think it would be good to add the back button to the all submenu

**Comment by singa2000** [comment]
I'm working it in the https://github.com/Samsung/TAU/pull/1218.
But still some submenu is missing the back button.
I'll add it.

**Comment by korneliakobiela** [comment]
@HunseopJeong development done, please review this feature and if everything is ok, please close this issue.

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
I think we can close the issue.
