### ISSUE TITLE
[Wearable] UIComponents VirtualList

### ISSUE THREAD

**Issue by HaYoung-Dev** [Samsung/TAU#1236]
Steeps to reproduce:

    1. Open the test page for the virtual list (wearable/UIComponents/contents/etc/list/virtual/normal.html)
    2. Modify the JSON_DATA as less data about 20 (wearable/UIComponents/contents/etc/list/virtual/virtuallist-db-demo.js).
    3. Scroll the page
    4. You can watch the error message on the console.

<hr/>

New > Tizen project > Sample > UIComponents 

When it is the last index, refer to an index that is more than the length of the data.

[normal.html]
<html>
<!DOCTYPE html>
<html>

<head>
	<meta content="width=device-width, initial-scale=1, user-scalable=no" name="viewport" />
	<link href="../../../lib/tau/wearable/theme/default/tau.css" rel="stylesheet" />
	<link href="../../../lib/tau/wearable/theme/default/tau.circle.css" media="all and (-tizen-geometric-shape: circle)" rel="stylesheet" />
	<link href="../../../css/style.css" rel="stylesheet" />
	<link href="../../../css/style.circle.css" media="all and (-tizen-geometric-shape: circle)" rel="stylesheet" />
	<script src="../../../js/circle-helper.js">
	</script>
	<script src="../../../lib/tau/wearable/js/tau.js">
	</script>
</head>

<body>
	<div class="ui-page" id="virtual-1line-page">
		<header>
			<h1>
				1 line
			</h1>
		</header>
		<div class="ui-content">
			<ul class="ui-listview" id="virtual-1line">
			</ul>
		</div>
		
		<script id="template-li-1line" type="text">
			<a>${NAME}</a>
   </script>
		<script>
			window.pageId = "virtual-1line-page";
			window.listId = "virtual-1line";
			window.templateId = "template-li-1line";
			window.itemClass = [];
		</script>
		<script src="virtuallist-db-demo.js">
		</script>
		<script src="virtuallist.js">
		</script>
	</div>
	<script src="../../../js/app.js">
	</script>
	<script src="../../../js/lowBatteryCheck.js">
	</script>
</body>

</html>

[virtuallist.js]
/*global pageId, listId, templateId, itemClass, tau, JSON_DATA */
(function (pageId, listId, templateId, itemClass) {
	var pageElement = document.getElementById(pageId),
		virtualListWidget,
		listHelper;

	/**
	 * pageshow event handler
	 * Do preparatory works and adds event listeners
	 */
	pageElement.addEventListener("pagebeforeshow", function () {
		/* Get HTML element reference */
		var listElement = document.getElementById(listId),
			bufferSize = 10,
			template = document.getElementById(templateId).innerHTML,
			options = {
				dataLength: JSON_DATA.length,
				bufferSize: bufferSize
			};

		if (pageElement.classList.contains("page-snaplistview")) {
			options.snap = {animate: "scale"};
		}
		virtualListWidget = tau.widget.Listview(listElement, options);
		/* Update list items */
		virtualListWidget.setListItemUpdater(function (listElement, newIndex) {
			var data = JSON_DATA[newIndex];

			/*jslint unparam: true*/
			listElement.innerHTML = template.replace(/\$\{index\}/ig, newIndex)
				.replace(/\$\{([\w]+)\}/ig, function (pattern, field) {
					return data[field];
				});
			/*jslint unparam: false*/

			if (itemClass.length) {
				itemClass.forEach(function (value) {
					listElement.classList.add(value);
				});
			}
		});
	});

	/**
	 * pagehide event handler
	 * Destroys and removes event listeners
	 */
	pageElement.addEventListener("pagehide", function () {
		// Remove all children in the virtual list
		virtualListWidget.destroy();

		if (listHelper) {
			listHelper.destroy();
		}
	});
}(pageId, listId, templateId, itemClass));

**Comment by lslachciak** [comment]
@hykim1 @HunseopJeong is this performance optimization? Could you describe more precisely how I can reproduce issue?

**Comment by HunseopJeong** [comment]
@lslachciak, No, it is bug. You can check the issue on the virtual list page(wearable/UIComponents/contents/etc/list/virtual/normal.html).
1. Modify the JSON_DATA as less data about 20 (/home/samsung/Source/opensource/TAU/examples/wearable/UIComponents/contents/etc/list/virtual/virtuallist-db-demo.js).
2. Scroll the page
3. You can watch the error message on the console.

**Comment by lslachciak** [comment]
thank you @HunseopJeong for clarification, coul you update this issue description with reproduction steps you mentioned?

**Comment by HunseopJeong** [comment]
@lslachciak, I updated the issue description.

**Comment by HaYoung-Dev** [comment]
@HunseopJeong 그리고 문제점이 하나 더 있습니다. 20개의 JSON1 data로 list create 한 다음, 100개의 JSON2 data로 virtual list를 그렸을때, 20개의 JSON1 data가 그려지고 21번째 부터는 JSON2 data 로 그려집니다.

**Comment by HunseopJeong** [comment]
@hykim1, 안녕하세요. 말씀해주신 부분이 잘 이해가 안되는데요.
JSON 1의 20개 data가 그려진 후에 JSON 2의 data가 0번부터 100개가 이어져서 그려야 한다는고 하시는건가요?

[기대동작]
1. JSON 1의 20개의 data로 virtual list를 만들어준다.
2. JSON 2의 100개의 데이터를 추가해준다.
3. JSON 1의 data가 20개가 그려진 후 JSON2의 100개의 데이터로 0번 부터 100개가 그려지길 희망한다

[실제동작]
1. JSON1의 20개의 data로 virtual list를 만들어준다.
2. JSON2의 100개의 데이터를 추가해준다.
3. JSON1의 data20개 그려지고 JSON2의 data가 21번부터 그려진다.

추가 질문사항으로 JSON2의 data를 JSON1에 어떤 식으로 추가하셨는지가 궁금합니다.

**Comment by HaYoung-Dev** [comment]
@HunseopJeong 아 네 다시 설명드리겠습니다.

[선제조건]
JSON data 파일 2개 (length가 20인 파일과 100인 파일)

[기대동작]
1. page show에서 length가 20인 JSON 파일의 data로 virtual list를 만든다.
2. page back 후 해당 list page 재진입 (이때 length가 100인 JSON 파일의 data로 virtual list를 만든다.) 
3. length가 100인 JSON의 data의 list만 보여진다.

[실제동작]
1,2 번의 동작을 했을 경우에 보여지는 화면은 0-19번까지의 데이터는 전에 그렸던 JSON의 데이터이며, 20번-99번까지의 데이터는 새로 그린 JSON의 데이터를 표시합니다.

즉, virtual list destroy시 data reset이 제대로 되지 않는 것 같습니다. 혹시 이해가 안되신다면 샘플코드 작성 후 전달 드릴까요?

감사합니다 :)

**Comment by HunseopJeong** [comment]
@hykim1,
아 무슨 말씀이신지 알것 같습니다.
말씀해주신 상황인거면 page back시 기존 listview가 제대로  destory가 되지 않는 걸로 생각이 됩니다.
혹시 샘플코드 작성이 어렵지 않다면 한번 올려주시면 확인해볼 수 있도록 하겠습니다.

**Comment by HaYoung-Dev** [comment]
@HunseopJeong 
https://github.com/hykim1/Tizen/tree/master/TAUListTest
리스트 테스트 중에 한 가지 문제가 더 발생해서 총 3가지 문제의 list 샘플 코드입니다. 
#1237 문제도 샘플에 추가해두었습니다.

**Comment by HunseopJeong** [comment]
@hykim1,
샘플 추가해주셔서 감사합니다.
제가 확인한 문제점이 맞는지 확인해주시면 감사드리겠습니다.
1.  1 list issue
-> 하나의 item으로 list를 만들면 error message가 나오는 이슈
2. virtuallist issue
-> 페이지를 뒤로가기 한뒤 다시 페이지 진입시 기존 item이 있고  21번터 추가되는 문제
3. scrollToPoistion issue
-> 화면이 깨진다고 말씀하시는게 transition 효과가 적용 안되는 문제인건가요?

**Comment by HaYoung-Dev** [comment]
@HunseopJeong 

1 list issue
-> 하나의 item으로 list를 만들면 error message가 나오는 이슈
네 맞습니다. console에 querySelector error가 발생합니다.
virtuallist issue
-> 페이지를 뒤로가기 한뒤 다시 페이지 진입시 기존 item이 있고 21번터 추가되는 문제
네 맞습니다.
scrollToPoistion issue
-> 화면이 깨진다고 말씀하시는게 transition 효과가 적용 안되는 문제인건가요?
아뇨 리스트 select가 가운데로 되지 않고 그 상태에서 스크롤 시 snaplist animation이 제대로 작동하지 않습니다. 제가 테스트 한 디바이스는 4.0 에뮬레이터입니다. tau 도 1.1.13으로 업그레이드 한 상태인데 맞게 된건지 이 부분도 확인부탁드려도 될까요?

**Comment by HunseopJeong** [comment]
@hykim1,
scrollToPoistion issue
-> 화면이 깨진다고 말씀하시는게 transition 효과가 적용 안되는 문제인건가요?
아뇨 리스트 select가 가운데로 되지 않고 그 상태에서 스크롤 시 snaplist animation이 제대로 작동하지 않습니다. 제가 테스트 한 디바이스는 4.0 에뮬레이터입니다. tau 도 1.1.13으로 업그레이드 한 상태인데 맞게 된건지 이 부분도 확인부탁드려도 될까요?
--> 4.0 에뮬레이터에서 테스트하셨군요. 네 알겠습니다 : D

**Comment by HunseopJeong** [comment]
@hykim1,
- 1 list issue -> 1.1.15버전에서 수정되었습니다.
- virtuallist issue -> 이부분은 https://github.com/Samsung/TAU/issues/1249 을 통해 확인해보겠습니다.
- scrollToPosition issue
-> 공유해주신 예제에서 현재 Listview를 중복적으로 생성하고 있습니다.
    index.html에 포함되어 있는 js/circle-helper.js파일의 경우 페이지에 ui-listview가 포함되어 있는 경우 tau.widget.ArcListview(list)를 생성하고 있습니다. 따라서 js/circle-helper.js를 제거하시거나 circle-helper.js에 아래와 같이 해당 page id를 추가시켜둔 후
```
&& page.id !== "page-scrolltoposition"
```
snaplistview2.js 안에
기존 SnapListStyle.create를 통해 생성하는 코드대신
```
listHelp = tau.widget.ArcListview(list);
listHelp.scrollToPosition(50);
```
과 같이 SnapListview 대신 ArcListview를 사용하는걸 권장드립니다.

**Comment by HaYoung-Dev** [comment]
@HunseopJeong 답변감사합니다. 1번 문제 해결되었습니다. 
scrollToPosition issue 에서 arcListview를 사용하지 않은 이유가 arcListview에서 touch event로 리스트를 이동했을 때, bounce effect 문제가 발생합니다. 공유 드린 샘플 코드에서도 발생하는 문제입니다.

[기대동작]
1. ArcListview 생성
2. listHelp.scrollToPosition(index) 으로 리스트 이동
3. touch 동작으로 리스트 이동 시도 (보통 아래에서 위로 움직일 때 자주 발생합니다.)
OR
3. scrollToPosition 애니메이션 중에 touch 동작으로 list scroll 시도
4. 마지막 리스트 index가 아닌데도 불구하고 하단에 bounce effect ui가 표시되고 touch 동작으로 아래의 리스트로 이동이 불가능합니다.

[실제동작]
4. rotary 동작과 동일하게 list 이동이 가능해야 한다.

**Comment by HunseopJeong** [comment]
@hykim1, 
#1256, #1257 
말씀해주신 이슈사항들을 수정한 패치가 현재 리뷰 중입니다.
관련 사항들을 확인하시려면 패치가 merge 된 후 최신 버전의 TAU(1.2.x)를
사용해주셔야 해당 수정사항을 확인 하실 수 있을 것 같습니다.

**Comment by HaYoung-Dev** [comment]
@HunseopJeong 지원해주셔서 감사합니다 :)

**Comment by HunseopJeong** [comment]
@hykim1, 
도움이 되셨다면 다행입니다 :D
언제든지 이슈사항이 있으시다면 말씀해주시면 감사드리겠습니다!
