### ISSUE TITLE
Router: Button with "data-rel='back'" & "href='#'" attributes causes loop on device Tizen 6.0

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#1238]
Test scenario:
- Install and open UIComponents app
- select 'Dialogs' >  'Picker Dialogs'
- tap back button (left top corner)

Issue:
- The app goes back to previous page but a while goes to the "Picker Dialogs" page

After analize of call stack I found difference between browser on pc and browser on device:
![obraz](https://user-images.githubusercontent.com/29534410/85520240-e8ca8e00-b602-11ea-80ed-e71d4fdb9ae9.png)

**Comment by TomaszLukawskiSam** [comment]
The issue is not 100% repeatable.
In case of proper result of button action, the log looks that:
![obraz](https://user-images.githubusercontent.com/29534410/85532143-bd9a6b80-b60f-11ea-8519-06ecb99f969a.png)

When the issue occurred the log looks different:
![obraz](https://user-images.githubusercontent.com/29534410/85532506-0a7e4200-b610-11ea-8800-968db61c8590.png)

I think the key to the problem is hash change. For example, if we remove `href="#"` from link then the log looks that:
![obraz](https://user-images.githubusercontent.com/29534410/85533288-af008400-b610-11ea-9fe0-5eb434c31888.png)

The `Router.open()` should be called once.

**Comment by TomaszLukawskiSam** [comment]
Hi @lslachciak ,
I made analysis of issue. I'll try to avoid second `Router.open` when there is `data-rel="back"' and hash is changing.

I think that `hash' change should be ignored when we are doing the history back.

**Comment by TomaszLukawskiSam** [comment]
I prepared fix for the issue.
Result in log:
![obraz](https://user-images.githubusercontent.com/29534410/85546766-8632bb80-b61d-11ea-94c0-4c118882269d.png)

**Comment by TomaszLukawskiSam** [comment]
Patch has been merged. I close the issue.

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
How you think? Move this change to 1.0?

**Comment by lslachciak** [comment]
if we move this change we should also update UIComponents app with @singa2000 commit adding back button
1.0-1.1 series is quite well tested so I don't think we should proapagate this change now

**Comment by TomaszLukawskiSam** [comment]
ok. We can close the issue.

**Comment by lslachciak** [comment]
@singa2000 issue which you reported us was fixed. Please close issue if you confirm on your side too.

**Comment by singa2000** [comment]
It's good working.
Thanks.
