### ISSUE TITLE
BottomButton: looks wrong in mobile profile

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#1241]
![obraz](https://user-images.githubusercontent.com/29534410/85571923-db2dfc00-b634-11ea-8050-4e2ba910b4fa.png)

UIComponents/components/buttons/contained/emphasis/medium-high-emphasis1.html

**Comment by korneliakobiela** [comment]
The development is done. Please review

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged. We can close the issue.
