### ISSUE TITLE
Sample home app creation

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1253]
Create sample home app for TV consisting of:
- cards (One UI style like in schedule App)
- apps icons
- grid layout

**Comment by singa2000** [comment]
- It also include the widgets in the cards (ex: video widgets, weather widgets)
  : It just enough widget image, not real widget.

**Comment by lslachciak** [comment]
How about following sample sections (cards):
- wheather
- news
- now on TV 
- my TV apps (grid layout)

**Comment by singa2000** [comment]
It looks good~
Thanks

**Comment by lslachciak** [comment]
App prepared and published
