### ISSUE TITLE
[HomeApp] Add widgets dynamically

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1270]
Use Case Scenario:

HomeApp have Weather Forecast and App on TV widgets only.
User clicks + button and popup appers
On the popup there are two widgets listed:
- "Latest News"
- "Now on TV"
User clicks one of items.
Popup is closed and new widget is added to HomeApp.

Notes:
+ button and popup are similar to those in the example
https://samsung.github.io/TAU/examples/1.2/examples/mobile/ScheduleApp/

**Comment by korneliakobiela** [comment]
PR Merged - please review

**Comment by lslachciak** [comment]
great, thank you
