### ISSUE TITLE
[HomeApp] Pull down on appbar refresh the app

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1271]
1. Visit https://samsung.github.io/TAU/examples/1.2/examples/mobile/HomeApp/
on Android google Chrome
2. Click Add to Home Screen
3. Click HomeApp icon on the home screen.
4. Pulling down App Bar
Observe:
refresh of HomeTV App occurs.

**Comment by lslachciak** [comment]
This makes unexpected behaviour.
Can we disable refresh when pulling down appbar?

**Comment by TomaszLukawskiSam** [comment]
Patch was merged.
