### ISSUE TITLE
[HomeApp] TV remote widget

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1277]
Add TV remote widget
Buttons on the widget should be clickable

**Comment by TomaszLukawskiSam** [comment]
@lslachciak What you think about ...

![image](https://user-images.githubusercontent.com/29534410/86911800-2f001100-c11c-11ea-98f1-afeecc85c104.png)

**Comment by lslachciak** [comment]
looks like remote control in Start Trek! nice :)

**Comment by TomaszLukawskiSam** [comment]
Patch was merged. Can we close the issue?

**Comment by lslachciak** [comment]
sure
