### ISSUE TITLE
Improve Karma test line coverage to 60%

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1278]
Current status as of 2020/07/08
npm run test:karma
53,96%

**Comment by TomaszLukawskiSam** [comment]
Latest status: 
![obraz](https://user-images.githubusercontent.com/29534410/87312435-da480600-c520-11ea-974e-27a05b1ed75e.png)

We need increase test coverage by 780 lines more.

**Comment by TomaszLukawskiSam** [comment]
Subtask: Appbar - increase test coverage (https://github.com/Samsung/TAU/issues/1299)

**Comment by lslachciak** [comment]
Subtask util/path coverage - https://github.com/Samsung/TAU/issues/1305

**Comment by lslachciak** [comment]
Latest status of coverage
Lines:   57.79%

**Comment by TomaszLukawskiSam** [comment]
I think we can close the issue.

**Comment by lslachciak** [comment]
we got it!
