### ISSUE TITLE
Some items not found in TAU samples

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#128]
--2019-05-27 15:38:01--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Actionbar/tw_ic_menu_detail_normal_holo_dark.png
Reusing existing connection to samsung.github.io:443.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:01 ERROR 404: Not Found.

--2019-05-27 15:38:01--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Actionbar/tw_ic_menu_detail_disable_holo_dark.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:01 ERROR 404: Not Found.

--2019-05-27 15:38:01--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Actionbar/tw_ic_menu_selectall_normal_holo_dark.png
Reusing existing connection to samsung.github.io:443.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:01 ERROR 404: Not Found.

--2019-05-27 15:38:01--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Actionbar/tw_ic_menu_selectall_disable_holo_dark.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:01 ERROR 404: Not Found.

--2019-05-27 15:38:01--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Progress/tw_progressbar_indeterminate1_holo_dark.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:01 ERROR 404: Not Found.

--2019-05-27 15:38:01--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Progress/tw_progressbar_indeterminate2_holo_dark.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:01 ERROR 404: Not Found.

--2019-05-27 15:38:01--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Progress/tw_progressbar_indeterminate3_holo_dark.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:02 ERROR 404: Not Found.

--2019-05-27 15:38:02--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Progress/tw_progressbar_indeterminate4_holo_dark.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:02 ERROR 404: Not Found.

--2019-05-27 15:38:02--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Progress/tw_progressbar_indeterminate5_holo_dark.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:02 ERROR 404: Not Found.

--2019-05-27 15:38:02--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/listview/tw_list_delete_holo_dark.png
Reusing existing connection to samsung.github.io:443.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:02 ERROR 404: Not Found.

--2019-05-27 15:38:02--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/listview/tw_list_setting_holo_dark.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:02 ERROR 404: Not Found.

--2019-05-27 15:38:02--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/listview/tw_list_add_holo_dark.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:02 ERROR 404: Not Found.

--2019-05-27 15:38:02--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_num_dot.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:02 ERROR 404: Not Found.

--2019-05-27 15:38:02--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_dialbtn_plus_normal.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:02 ERROR 404: Not Found.

--2019-05-27 15:38:02--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_dialbtn_plus_pressed.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:02 ERROR 404: Not Found.

--2019-05-27 15:38:02--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_dialbtn_plus_dim.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:03 ERROR 404: Not Found.

--2019-05-27 15:38:03--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_dialbtn_minus_normal.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:03 ERROR 404: Not Found.

--2019-05-27 15:38:03--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_dialbtn_minus_pressed.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:03 ERROR 404: Not Found.

--2019-05-27 15:38:03--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_dialbtn_minus_dim.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:03 ERROR 404: Not Found.

--2019-05-27 15:38:03--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_wheel_01.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:03 ERROR 404: Not Found.

--2019-05-27 15:38:03--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_left_softbtn.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:03 ERROR 404: Not Found.

--2019-05-27 15:38:03--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_right_softbtn.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:03 ERROR 404: Not Found.

--2019-05-27 15:38:03--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_time_bg.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:03 ERROR 404: Not Found.

--2019-05-27 15:38:03--  https://samsung.github.io/TAU/examples/wearable/UIComponents/lib/tau/wearable/theme/default/images/Datetimepicker/tw_timepicker_num_dot_01.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:03 ERROR 404: Not Found.

--2019-05-27 15:38:04--  https://samsung.github.io/TAU/examples/wearable/UIComponents/extra/images/Controller_icon/tw_btn_next_depth_holo_dark.png
Reusing existing connection to samsung.github.io:443.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:04 ERROR 404: Not Found.

--2019-05-27 15:38:04--  https://samsung.github.io/TAU/examples/wearable/UIComponents/extra/images/Controller_icon/tw_btn_next_depth_disabled_holo_dark.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:04 ERROR 404: Not Found.

--2019-05-27 15:38:04--  https://samsung.github.io/TAU/examples/wearable/UIComponents/extra/images/Controller_icon/tw_btn_next_depth_focused_holo_dark.png
Connecting to samsung.github.io (samsung.github.io)|185.199.110.153|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-27 15:38:04 ERROR 404: Not Found.

**Comment by pkaczmarczy** [comment]
PR has been already merged
