### ISSUE TITLE
Check negative TC ratio

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1281]
Check negative/positive TC ratio for Karma

**Comment by TomaszLukawskiSam** [comment]
Scope of task:
- how to mark TC as negative or how to detect negative TC?

**Comment by lslachciak** [comment]
We ca mark negative TC in test names.
In such case I don't see relation to assertions number. When counting assertions we don't care if they are positive or negative.

**Comment by lslachciak** [comment]
I'm suspending this issue. We are considering tailoring for this.
