### ISSUE TITLE
Check number of assertions in karma tests

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1282]
Check number of assertions in karma tests

**Comment by TomaszLukawskiSam** [comment]
I think this task contains in https://github.com/Samsung/TAU/issues/1281
We need number of assertions in Karma to check positive/negative TC ratio.

**Comment by TomaszLukawskiSam** [comment]
Format of JUnit XML assumes the number of assertions as optional.
(https://llg.cubic.org/docs/junit/)
eg.
```
<testsuites tests="3" failures="1" disabled="0" time="2.198166">
	<testsuite tests="3" time="0.223076" errors="0" failures="1" skipped="0" timestamp="2018-08-27 06:56:50Z" name="TestsClass">
		<testcase name="Test1" assertions="1" time="0.023290" status="Passed" classname="TestsClass" />
```

I try to explain why the number of assertions is not passed to the report.

**Comment by TomaszLukawskiSam** [comment]
This task seems suspended because (https://github.com/Samsung/TAU/issues/1281)
