### ISSUE TITLE
[Sonar] Appbar.js Sonar issue

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1295]
src/js/core/widget/core/Appbar.js
Warning Message
Move the declaration of "nominalHeights" before this usage.
![image](https://user-images.githubusercontent.com/2246331/87132786-aa85cd80-c296-11ea-8d2b-9fa44cccf53a.png)

**Comment by TomaszLukawskiSam** [comment]
I think the issue can be close.
