### ISSUE TITLE
Multiline toast message

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1303]
Wrap toast message text into multilines
See example:
![image](https://user-images.githubusercontent.com/2246331/87422760-7fbeb080-c5d9-11ea-84c1-985d708b139c.png)

More details: Web App Basic Component UI v 1.9

**Comment by TomaszLukawskiSam** [comment]
I think the issue can be close.

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged. We can close the issue. Due to @lslachciak holidays I close the issue.
