### ISSUE TITLE
Krama util/path coverage is only 19.42%

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1305]

**Comment by lslachciak** [comment]
Status
Testing tests/js/core/util/path/path.html 
phantom
...........................OK
>> 72 assertions passed (39ms)
>> Coverage:
>> -  Lines: 22.28%
>> -  Statements: 22.28%
>> -  Functions: 17.25%
>> -  Branches: 9.22%
karma:
Chrome 83.0.4103 (Linux 0.0.0) ERROR: TypeError{}
Chrome 83.0.4103 (Linux 0.0.0): Executed 0 of 0 ERROR (0.086 secs / 0 secs)
%Lines 14.49

**Comment by lslachciak** [comment]
PR merged
