### ISSUE TITLE
[Wearable] The height of the Arclist and the height of the scroll do not match.

### ISSUE THREAD

**Issue by HaYoung-Dev** [Samsung/TAU#1318]
Reproduce steps
1. click 
2. scroll down to end 
3. back key press 
4. repeat 1~3

[Expected]
The height of the Arclist and the height of the scroll should match.

[Actual]
The height of the Arclist and the height of the scroll do not match.
The list does not end position. The scroller is marking the end.
Maybe destroy function has a problem. 

![arcListView_issue](https://user-images.githubusercontent.com/28881840/87918560-92d9f080-cab1-11ea-8b47-68e5fcc53b1c.png)

Here is Sample Code:
https://github.com/hykim1/Tizen/tree/master/TAUListArcListView

**Comment by HunseopJeong** [comment]
@hykim1, 
Sorry for late answer.
I will check it.

**Comment by HunseopJeong** [comment]
@hykim1, fix patch was merged.
You can check it in latest release version.
