### ISSUE TITLE
Floating Action button - implementation and example

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#1322]
2-5 Floating Action Button (UI 1.9)

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged. I think we can close the issue.

**Comment by lslachciak** [comment]
@TomaszLukawskiSam is selected state also implemented?
![image](https://user-images.githubusercontent.com/2246331/89905191-294d8d80-dbea-11ea-9575-8d477e819a60.png)

**Comment by TomaszLukawskiSam** [comment]
I afraid that I don't know what means this state of FAB. The selected state is not described in GUI.

**Comment by lslachciak** [comment]
OK, I'll try to clarify this
We will create new issue for this when clear
