### ISSUE TITLE
Checkbox - Thumbnail List

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1324]
See GUI 3-1

**Comment by lslachciak** [comment]
Current status
![image](https://user-images.githubusercontent.com/2246331/88178164-3ea64c00-cc2a-11ea-92d9-dc5cbdc584f3.png)
Issue: need to have icons not having empty space around

**Comment by lslachciak** [comment]
done in https://github.com/Samsung/TAU/pull/1341
