### ISSUE TITLE
Expand Button

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1327]
See GUI
3-6 Expand Button

**Comment by TomaszLukawskiSam** [comment]
This task is dividing for several smaller tasks:
- Expandable button: List type - this case is already implemented only GUI needs verification #1334 
- Expandable button: Text field type - no example in UIComponents #1335
- Expandable button: Card type - not implemented, no example #1336 
- Expandable button: List in Card type - not implemented, no example #1337

**Comment by TomaszLukawskiSam** [comment]
All sub tasks have already been done. I think we can close the issue.

**Comment by lslachciak** [comment]
works fine
