### ISSUE TITLE
document.registerElement - deprecated API usage in TAU

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#133]
TAU uses document.registerElement API which is deprecated now
```
src/js/core/widget/customElements.js:						registeredTags[tagName] = document.registerElement(tagName, registerQueue[tagName]);
src/js/core/widget/customElements.js:			if (typeof document.registerElement === "function" && ns.getConfig("registerCustomElements", true)) {

```
This should be done before https://bugs.chromium.org/p/chromium/issues/detail?id=660759 is closed

**Comment by TomaszLukawskiSam** [comment]
Deprecated CustomElement API has removed by commit: https://github.com/Samsung/TAU/commit/a9a76d55fb5a93f5dd79b467898f6569246a1ce4

@lslachciak 
Can the issue close?
