### ISSUE TITLE
Controllers - Chips

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1330]
Controllers - Chips
Se GUI  (3-8) Chips

**Comment by TomaszLukawskiSam** [comment]
Known issue:

Spacing on the bottom of chips.
According to the guideline bottom space should be 0.

![image](https://user-images.githubusercontent.com/29534410/89016116-73945c00-d318-11ea-87c2-4547a9ba06ff.png)

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
I think we can close the issue. Known issue I added to milestone.

**Comment by lslachciak** [comment]
works fine, thank you
