### ISSUE TITLE
[Wearable] How do I change the color of the scrollbar?

### ISSUE THREAD

**Issue by HaYoung-Dev** [Samsung/TAU#1350]
I want to change the color of the scrollbar.
I try to change the color in tau.css (.scrolling-scrollbar .scrolling-scrollthumb) but i cant..
How do i?

**Comment by HunseopJeong** [comment]
@hykim1,
The scrollbar was controllered by the tizen webengine.
So we don't change the color of the scrollbar currently.
If you want to change the color, disable the tizen scrollbar and create a custom circular scrollbar.
I think it is a neccessary feature to help the development.
I will consider adding that feature.

**Comment by HaYoung-Dev** [comment]
@HunseopJeong We are trying to create custom circular scrollbar. But we couldn't hide it perfectly. How to disable the tizen scrollbar?

**Comment by HunseopJeong** [comment]
@hykim1,
Unfortunately, there is no API.
If you remove the "tizen-circular-scrollbar" attribute at the "ui-scroller" and "ui-content", you can hide the scrollbar.
I will add the API to disable the scrollbar.

**Comment by HunseopJeong** [comment]
@hykim1, 
You can hide the scrollbar with 'enableCircularScrollbar' option after #1364.

```
document.addEventListener('tauinit', function() {
  tau.setConfig('enableCircularScrollbar', false);

  // Your code
})
```
