### ISSUE TITLE
(16-1)Thumbnail grid

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU#1354]
See GUI (16-1) Thumbnail grid

**Comment by singa2000** [comment]
If you implement done  "Controllers" components, would you start the "Thumbnail" components, please?

**Comment by TomaszLukawskiSam** [comment]
I'm adding this task to current Milestone, now

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged. We can close the issue.
