### ISSUE TITLE
[HomeApp] Bad path to webclips server.

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU#1376]
Some HTTP request to web clip server is resolved `http://localhost:8888/examples/mobile/HomeApp/api/webcliplist`, but the server is on the other port.

**Comment by TomaszLukawskiSam** [comment]
You have to start HomeApp from `examples/mobile/HomeAppServer` by `npm start`, then open `localhost:3000` in browser.

**Comment by lslachciak** [comment]
@korneliakobiela please reopen issue if still problem after @TomaszLukawskiSam comment
