### ISSUE TITLE
[HomeApp] Improve section changer refresh

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1395]
Section changer requires to be refreshed on timeout after creation
window.setTimeout(function () {
	tau.engine.getBinding(sectionChanger).refresh();
}, 200);

See https://github.com/Samsung/TAU/pull/1394 for more details

**Comment by TomaszLukawskiSam** [comment]
I try to verify the issue. At the moment I know that the reason of issue is not in Section Changer but in style.css. The Section Changer is building before webclip styles are loaded. This loading can be improved.

**Comment by TomaszLukawskiSam** [comment]
I think we can close the issue.
