### ISSUE TITLE
[HomeApp] Improve AppsOnTV webclip

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1421]
Improve AppsOnTV webclip.

Requirements:
- scrollable horizontal list of apps on bottom
- for each selected app - horizontal list of images on top appears

**Comment by lslachciak** [comment]
@TomaszLukawskiSam how about closing issue?

**Comment by TomaszLukawskiSam** [comment]
I think we can close the issue.

**Comment by lslachciak** [comment]
right
