### ISSUE TITLE
[HomaApp] All webclips urls should be validated

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1431]
All webclip urls should be validated because local storage can keep not up-to-date webclips list.

**Comment by singa2000** [comment]
As you known, please consider both local storage and hosted  url.

**Comment by lslachciak** [comment]
Yes, we will consider both.
After this PR https://github.com/Samsung/TAU/pull/1425 we will store whole appslist in local storage.
So when starting up again app no need to connect with remote server to get webclip list. But I think we need to validate if there are webclips not longer existing on server.

**Comment by lslachciak** [comment]
PR merged
