### ISSUE TITLE
[HomeApp] Apply ordering rules to app

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1437]
Apply following ordering rules to HomeApp:

1. WebClips for active apps are always before WebClips for inactive
2. Control cards are always before service cards

**Comment by lslachciak** [comment]
Currently we are discussing need of control card, so please implement point 
`1. WebClips for active apps are always before WebClips for inactiv`
first

**Comment by lslachciak** [comment]
Ordering by app active was done in app
    // check apps order
        appsList = appsList.sort(function (app1, app2) {
            return (app1.isActive) ?
                (app2.isActive) ? 0 : -1 : 1
        });

**Comment by lslachciak** [comment]
Basing ordering by active app is already done
