### ISSUE TITLE
[HomeApp] Uncaught (in promise) undefined when no connection to server

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1451]
When no connection to server there is console error:
[HomeApp] Uncaught (in promise) undefined when no connection to server

I think we should handle all errors

how to test:
1. run http-server
`/home/l.slachciak/.nvm/versions/node/v10.15.3/bin/http-server`
2. visit:
http://X.X.X.X:8080/examples/mobile/HomeApp/
3. observe console

**Comment by lslachciak** [comment]
Issue no longer exists.
Instead I can see:
Error getting app lits: Unexpected end of JSON input
