### ISSUE TITLE
HomeAppTV: rebuild method `updateWebClipsUI` so that the list is updated instead of being cleared and built

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#1454]

**Comment by lslachciak** [comment]
@TomaszLukawskiSam I think you did it as a part of https://github.com/Samsung/TAU/pull/1467

**Comment by TomaszLukawskiSam** [comment]
No, it is still to do. We can move this issue to Milestone 8

**Comment by TomaszLukawskiSam** [comment]
The issue has already been fixed.
