### ISSUE TITLE
[HomeApp] Apps on TV is being removed

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1468]
Reproduction steps:

1. Run http-server
2. visit http://X.Y.Z.Q:8080/examples/mobile/HomeApp/
3. clean applicaiton Local storage (F12 + Application --> local Storage)
4. refresh page
5. click + icon
6. click OK
Observe:
Apps on TV webclip is no longer visible

**Comment by TomaszLukawskiSam** [comment]
We can close this issue.
