### ISSUE TITLE
TAU versions question

### ISSUE THREAD

**Issue by DevronB** [Samsung/TAU#1471]
I can see docs on TAU 1.0 and 1.0 with Tizen version compatibility. Can someone explain to me where TAU 1.2 comes in and if I'm going to update from TAU 1.0 should I go straight to TAU 1.2? Maybe I'm missing something here??

**Comment by lslachciak** [comment]
TAU 1.2 is prepared with intention to support Tizen 6.0 release with OneUI 2.0 implementation.
We try to keep Semantic Versioning Specification so for wearable 1.2 adds new functionalities (APIs) in comparison with 1.1 but we try to keep semantic of old 1.x API untouched. So old wearable apps using 1.x API should switch to 1.2 API smoothly from the API point of view. But to be compatible with OneUI 2.0 look and feel some visual changes may be required in the app itself.

**Comment by DevronB** [comment]
Thank you. So to clarify, I'm currently on TAU 1.0 and should have minimal issues switching directly to 1.2? My app currently targets Tizen 4+

**Comment by lslachciak** [comment]
Theoretically there should not be any issue. API is still supported.
But please be aware that OneUI 2.0 controls may not fit your app exactly.
Also TAU 1.2 was not officially released with Tizen 6.0 and I'm not able to confirm when it will be.

**Comment by DevronB** [comment]
Thank you
