### ISSUE TITLE
modifying changeable theme

### ISSUE THREAD

**Issue by DevronB** [Samsung/TAU#1478]
Hi, are there any docs/readme on changing the changeable theme?

I've tried modifying the theme.colorPalette.less which seemed to work from some things but not all. I'd like to change the 'bouncing effect' and scrollbar colours. But a comprehensive overview on how to re theme would be good.

Can you point me in the right direction please?

TAU 1.2

Cheers

**Comment by DevronB** [comment]
Any comment on this? if there is nothing, I can deal with that... I'm just wondering if there's some documentation I've missed.

if there's no docs, maybe a few tips on what files I should be looking at changing??

Cheers

**Comment by DevronB** [comment]
ok, so I have the bouncing effect colour changed. But I can't workout the scrollbar colour. Can I get some help on how/where to change this please?

![image](https://user-images.githubusercontent.com/27395345/99197842-c8cf7d00-27e4-11eb-8cfd-77c18503939a.png)

**Comment by TomaszLukawskiSam** [comment]
Dear @DevronB ,
The scroll indicator is part of web engine. TAU for wearable doesn't try to modify it.
However, I will try to check methods to customise this scroll indicator in web engine.

**Comment by singa2000** [comment]
Dear @DevronB 
Thanks for your question.
As Thomas said, the scroll indicator is part of web engine. So I'm sorry but TAU can't change the color.
And TAU don't have the plan for it.
I hope you understand.
Thanks

**Comment by DevronB** [comment]
That's a shame, SHealth and other apps have the ability to do this. TAU/web seems to have some shortcomings compared to native etc. In my opinion, little things like this affect the professionalism of apps. Surely this can be looked into with the web platform team? Also, no comment on how best to theme in TAU as per original question?

**Comment by TomaszLukawskiSam** [comment]
Dear @DevronB ,

There is only one color theme in the circular profile. Unfortunately Its implementation is heavily outdated. In my opinion, it's best to just overwrite the appropriate styles.
In mobile profile 1.2 we use css variables like `var(--color)` it works well for creating and changing a theme. You can check this if you need.

The second thing is changing the scrollbar styles. This issue has been reported and discussed many times however, it was not implement such functionality into the web engine.

Now, I will try to check rest of issues reported by you.

**Comment by DevronB** [comment]
Thanks for the info. I'll continue to overwrite styles and use var(--) as I have been for now.
