### ISSUE TITLE
Wearable Tizen 5.5 list screenshots

### ISSUE THREAD

**Issue by DevronB** [Samsung/TAU#1481]
On Tizen 5.5 the screen shot feature is now a press of the top and bottom buttons. When a screenshot is take in a list you get the opportunity to press the chevron icon to keep scrolling the list taking more screenshots to append. In TAU arclistview this icon appears but does not scroll the list, it just appends the current view repeatedly. Is this an oversight or do I need to implement something for this to work?

TAU 1.2

Cheers
Devron
![Screen_20201030_164730](https://user-images.githubusercontent.com/27395345/97667527-05eefc00-1ad0-11eb-97b7-f4156100e911.png)

**Comment by TomaszLukawskiSam** [comment]
Hi,
Interesting issue but I think hard to fix. We didn't take account this scenario. I have to check possibility to fix it.

**Comment by DevronB** [comment]
Thanks, it would be very helpful if this could work. It's handy for documentation and user feedback.

**Comment by DevronB** [comment]
Oh, and screenshot seems to be aware it's taking a screenshot of a list at least too.
