### ISSUE TITLE
Number Spinner with < 13 items not rendering correctly

### ISSUE THREAD

**Issue by DevronB** [Samsung/TAU#1486]
I've been using the NumberPicker in TAU 1.0 which was based on wearable Spin. This was working fine for me. Now that I have upgraded to TAU 1.2 one of my number pickers with only 6 items is not rendering correctly. I think in TAU 1.2 the Spin widget was pushed to core and some changes in this have broken it when there are fewer items. I'm thinking it has something to do with:
Spin NUMBER_OF_CAROUSEL_ITEMS = 13, and when there are less there is some problem with the logic. It's not obvious to me if this can be reduced. I tried setting this to NUMBER_OF_CAROUSEL_ITEMS = 6 (my min) but it seemed to have some undesired effects.

Cheers

**Comment by DevronB** [comment]
Any chance this could be looked into soon? I'm trying to get my app update to store but this is holding it up.

Cheers

**Comment by DevronB** [comment]
In addition to this, the NumberPicker/Spin widget in tau_1.2 does not work well when dragging. Drag target should be document, but it seems the target is the spin element control only. Dragging does not seem natural, and if you change direction it looses the drag somehow. When dragging up the whole spinner moves up on the page. Also, when using the bezel and spinning from max to min (end of spin list) the spinner scrolls completely in reverse order, back to the max. 

It was working fine in tau_1.0, but the spin/number picker seem to have had a rewrite at some stage.

All this behaviour can be observed in examples/UIComponents too.

It would be great if this could be looked at soon as it's holding me up from using TAU_1.2 and I'm sort of invested now.

Cheers

**Comment by DevronB** [comment]
@TomaszLukawskiSam

**Comment by DevronB** [comment]
and, there's no vibration feedback when dragging like the tau_1.0 version

**Comment by DevronB** [comment]
A few things I've found if it helps:

- Issues occur when Number Picker/Spinner has <13 Items.
- Spin widget is not destroyed when Number Picker is destroyed, causes issues if new NP is created later
- I think if I set NUMBER_OF_CAROUSEL_ITEMS= to even number it causes issues, setting this to 5 seemed to work as my minimum number of items is 6. I tried making this dynamic, <NUMBER_OF_CAROUSEL_ITEMS ? items.length : NUMBER_OF_CAROUSEL_ITEMS but this caused issues on recreation of new NP because NUMBER_OF_CAROUSEL_ITEMS is not reset on rebuild. Tried putting this logic in Spin._build, but it seems build is called before _init, _init has length logic need for dynamic NUMBER_OF_CAROUSEL_ITEMS calc.
- I had to hardcode the dragTarget = document, because although the logic looks like this should be the case somehow it's not. This hardcoding seemed to fix the dragging issues.

I also added the vibration logic from TAU_1.0 back in, seems to be working fine.

So after a few hacks I got this working in my project, but getting these addressed properly would be great.

Cheers

**Comment by TomaszLukawskiSam** [comment]
Thank you very much for the detailed problem analysis. Now, I will try to make fixes.

**Comment by DevronB** [comment]
Confirming fixes applied for this seem to be working ok my end, thank you.

**Comment by DevronB** [comment]
Although, the spin full reverse spin is still occurring using the rotary event and loop at the end of the list?

**Comment by TomaszLukawskiSam** [comment]
I think that issue can be closed. Please create new issue if still exists.
