### ISSUE TITLE
npm run build fails on the latest repo

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#1504]
reproduction steps:
git fetch origin
git reset --hard origin/tau_1.2
git clean -dfx
npm install
npm run build

Observe:
Running "svg-sprites:mobile" (svg-sprites) task
convert: src/css/profile/mobile/theme-changeable/images/3_Controllers/Checkbox/
convert: src/css/profile/mobile/theme-changeable/images/3_Controllers/Radio/
(node:5510) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token ...
(node:5510) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token ...

**Comment by TomaszLukawskiSam** [comment]
I found issue in module `css-tree`. Probably implementaion has been changed and now `spread` syntax is required.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

```
node_modules/csso/node_modules/css-tree/lib/syntax/config/mix.js:23
        ? { ...value }
            ^^^
```

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
Can I close the issue?

**Comment by lslachciak** [comment]
Closing issue

**Comment by lslachciak** [comment]
Thank you fir fix
