### ISSUE TITLE
Number Picker Port from wearable to mobile

### ISSUE THREAD

**Issue by DevronB** [Samsung/TAU#1537]
Now Spin is in core, and the NumberPicker is now a spin control, wouldn't a port of NumberPicker to mobile be relatively simple? Could this be done? Other mobile platform has this number spin feature available... please? :-)

**Comment by TomaszLukawskiSam** [comment]
The Spin widget has already been implemented in mobile profile. The NumberPicker is not directly implemented but you can use Spin widget. You can check how it works in Dialogs (./examples/mobile/UIComponents/components/dialogs/picker.html)

**Comment by DevronB** [comment]
Great, thanks for the fast reply. I've tried this and it seems to work well. Only thing I found is the opacity on .ui-spin-item is set to:  var(--spin-item-opacity)!important = .1 which seems far too low in my tests.
