### ISSUE TITLE
Dialog: Value picker

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#1542]

**Comment by DevronB** [comment]
Assuming this is a mobile "Number Picker", I would be keen for this :-)

Or, even if just an example of using core- Spin correctly.. I have this working but I think there are some display issues, like opacity and transform on non active spin items, but it could just be my implementation.

**Comment by TomaszLukawskiSam** [comment]
Patch has been merged. I close the issue.
