### ISSUE TITLE
Floating actions example  - not working

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#156]
Reproduction steps:
1. Visit:
https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/controls/floatingactions/on-page.html
2. Not possibleto make any action

**Comment by TomaszLukawskiSam** [comment]
Floating Button doesn't support mouse events - supports only touch events.

**Comment by TomaszLukawskiSam** [comment]
After verification I have to change conclusions. Floating Button supports mouse events.The issue is more complicated and I have proofs that it can be issue in web browser engine.

**Comment by lslachciak** [comment]
@TomaszLukawskiSam  PR was merged, can we put this issue into review?

**Comment by TomaszLukawskiSam** [comment]
I think that we can close the issue.
