### ISSUE TITLE
Dialog click event only working on the popup button

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU#1578]
Just I have a question.
In the dialog button. I want to just work the click event in the popup button.
If the user click the background of dialog, the dialog don't close.

I want to 4th  "CLICK ME" of  Modal window in the  https://stephanwagner.me/jBox

**Comment by TomaszLukawskiSam** [comment]
This option of Dialog is realized by `data-dismissible="false"`  eg.
```
<div class="ui-popup" data-dismissible="false">
```

**Comment by singa2000** [comment]
Thanks. It's good working.

data-dismissible="false" is just option for Dialog?

**Comment by TomaszLukawskiSam** [comment]
Yes.

**Comment by singa2000** [comment]
Thanks for your quick response

**Comment by TomaszLukawskiSam** [comment]
This is an example that the page with combinations of all available options for a given set is missing from the TAU.
