### ISSUE TITLE
UIComponents app button in searchbar takes whole screen

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU#160]
This happens on mobile and wearable profile.
Path: UIComponents/components/controls/searchbar/searchbar-with-icon.html
![image](https://user-images.githubusercontent.com/38784474/60098880-c9cabf00-9756-11e9-95d7-f72cbcdfdb93.png)
Probably this button should be placed like little button in left corner (currently there is not enough space to show textInput)
The button is missing ui-btn-icon class.

**Comment by TomaszLukawskiSam** [comment]
@pkaczmarczy 

The issue is solved by patch for another issue (#288).

**Comment by pkaczmarczy** [comment]
The patch solved the problem.

![Screenshot from 2019-08-16 14-18-42](https://user-images.githubusercontent.com/38784474/63167197-d66de400-c030-11e9-9d74-1a18ceb08008.png)
