### ISSUE TITLE
checkbox items don't have marquee animation

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#161]
Reproduction steps:

1. Open https://samsung.github.io/TAU/examples/wearable/UIComponents/ in Google Chrome
2. Run Developer mode and define device: 360x360
3. Go to Controls-->Checkbox
4. Observe: Checkbox items don't have marquee animation

![image](https://user-images.githubusercontent.com/2246331/60141983-cab12e80-97f2-11e9-845b-cf9fc169d485.png)

**Comment by TomaszLukawskiSam** [comment]
This issue has been probably resolved by path for another issue. Please recheck it for TAU 1.0.5

**Comment by lslachciak** [comment]
I can't reproduce this issue currently on tyhe site: https://samsung.github.io/TAU/examples/1.0/examples/wearable/UIComponents/contents/controls/checkbox.html
because no overlap occurs
