### ISSUE TITLE
TAU 1.2 AssistPanel events not working

### ISSUE THREAD

**Issue by DevronB** [Samsung/TAU#1648]
In the example for the wearable assist panel it hooks up the following events:

	/**
	 * Assist Panel open event handler.
	 * Enables assist panel rotary scrolling
	 */
	page.addEventListener("assistpanelopen", function () {
		tau.util.rotaryScrolling.enable(page.querySelector(".ui-assist-panel"));
	});

	/**
	 * Assist Panel close event handler
	 * Enables scroller for assist panel page
	 */
	page.addEventListener("assistpanelclose", function () {
		tau.util.rotaryScrolling.enable(page.querySelector(".ui-scroller"));
	});

These events are never fired. I need to disable scrolling on a selector when the assist panel is closed, but these events do not get fired. Am I missing something or is this a bug?

**Comment by TomaszLukawskiSam** [comment]
@DevronB 

You are right. These events are not triggering.
The AssistPanel inherits from Drawer widget. At the moment you can use "draweropen", "drawerclose" events.
I'll prepare patch for "assistpanelopen" and "assistpanelclose". Sorry for inconvenient.

**Comment by DevronB** [comment]
Thank you! and thank you for the workaround events, these are working fine.

Cheers

**Comment by TomaszLukawskiSam** [comment]
Patch has been merged. I think I can close the issue.
