### ISSUE TITLE
Selector popup & Opacity

### ISSUE THREAD

**Issue by SandraAlfaro** [Samsung/TAU#1663]
Hi,
I'm trying to put a "transparent" background for the selector (only the background, the items/button must remain opaque).
I tried using ``opacity: 0.3;`` on the ``.ui-popup`` and putting the ``ui-selector`` or the ``ui-item`` opacity to 1.
But instead of having only the background with an opacity of 0.3, i have all the selector popup, items/buttons included.
I also tried with ``background: rgba();`` but it doesn't work at all.
Below the code html and css for the selector and its opacity and the image in result.

I don't know if it's a real issue/error, or if i'm doing something wrong and in that case i would like to have some help or advice.

HTML :
![html](https://user-images.githubusercontent.com/38646622/112817546-d9410f80-9082-11eb-9bd1-b03e542e2d7c.png)

CSS : 
![css](https://user-images.githubusercontent.com/38646622/112817567-e231e100-9082-11eb-92c0-e09becff784c.png)

Result : 
![result](https://user-images.githubusercontent.com/38646622/112817744-10afbc00-9083-11eb-8168-8c8ff959c631.png)

**Comment by TomaszLukawskiSam** [comment]
The `opacity` for `.ui-popup` is wrong idea.
Only `background-color: rgba(,,,0.3)` make sense.
I will check this while a moment

**Comment by TomaszLukawskiSam** [comment]
You can check:
```
.ui-popup {
	background-color: transparent;
}
.ui-selector {
	background-color: transparent;
}
```

**Comment by SandraAlfaro** [comment]
That works ! Thanks a lot ! 
By the way, with the transparency i found that when you scroll with the bezel ring to change from one selector item/button to an other one, the page under scrolls too. If i'm not wrong it should only scroll on the selector so, I don't know why this is or how to fix it. (2 Images below)

With the 1º item selected (top of the page under)
![top-item1](https://user-images.githubusercontent.com/38646622/112870625-b2a0ca00-90be-11eb-811c-f2f49b45a3ca.png)


With an other item selected (middle of the page under)
![middle](https://user-images.githubusercontent.com/38646622/112870834-e54ac280-90be-11eb-9fe8-5e1da839b3c3.png)

**Comment by TomaszLukawskiSam** [comment]
Hi :)

I think the second issue is similar to issue https://github.com/Samsung/TAU/issues/1648
But instead of AsistantPanel you use Popup, so I'm  supposing that code similar to below resolve the issue:
```
/**
 * Disable rotary scrolling on content under popup
 */
page.addEventListener("popupbeforehide", function () {
	tau.util.rotaryScrolling.disable(page.querySelector(".ui-scroller"));
});

/**
 * Enables scrolling for page
 */
page.addEventListener("popupbeforeclose", function () {
	tau.util.rotaryScrolling.enable(page.querySelector(".ui-scroller"));
});
```

**Comment by SandraAlfaro** [comment]
I tested it. It doesn't seem to work.
i was asking myself why should i disable the roratyScroll on ``popupbeforehide`` to enable it on ``popupbeforeclose`` ?
Souldn't be better to disable the scroll when the popup shows (or the page hides) ?

**Comment by TomaszLukawskiSam** [comment]
I think you should disable scrolling of page content when popup is showing and enable scrolling again when popup is closing.

If you can attach the application, I will try to verify the problem.

**Comment by SandraAlfaro** [comment]
I tested like you said and it worked out for the disable but i can't enable after.
So I disable the scroll of the page when i click on the more-options button that opens the selector menu with 
``tau.util.rotaryScrolling.disable`` on the page.
But when i try to enable it when closing the selector with ``tau.util.rotaryScrolling.enable`` it doesn't seem to work.

**Comment by SandraAlfaro** [comment]
You can find in the ``.zip`` a demo that is based on a TAU List with a more-options button that opens a selector.
It should be enought to test the issue. 
So, at first i can scroll on the page, then when i open the selector the scroll on the page stops (as wanted) but when i leave/close the selector the scroll on the page doesn't come back on.
[TestsTizen.zip](https://github.com/Samsung/TAU/files/6245797/TestsTizen.zip)

**Comment by TomaszLukawskiSam** [comment]
Hi :)

You missed `page.querySelector(".ui-scroller")`. Please check attached file: 
[TestsTizen-fixed.zip](https://github.com/Samsung/TAU/files/6249481/TestsTizen-fixed.zip)

**Comment by SandraAlfaro** [comment]
Ok, i understand now ! Thanks a lot !

**Comment by TomaszLukawskiSam** [comment]
I close the issue.
