### ISSUE TITLE
Add unit tests for Graph widget

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU#177]
There are no unit tests for Graph widget.

**Comment by lslachciak** [comment]
@pkaczmarczy please share current status of this issue here - in progress/susended/PR ready etc..

**Comment by pkaczmarczy** [comment]
Currently work on this issue is suspended because of higher priority tasks.

**Comment by TomaszLukawskiSam** [comment]
The issue is complicated because command line test engine (based on PhantomJs) is not supporting bundle file.

**Comment by TomaszLukawskiSam** [comment]
The PR has already merged.
