### ISSUE TITLE
Listview broken background after adding element

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU#182]
After adding element to already built widget background canvas is broken.

![image](https://user-images.githubusercontent.com/38784474/60591524-f1490980-9d9e-11e9-95ab-bee75cc174ac.png)

**Comment by TomaszLukawskiSam** [comment]
@pkaczmarczy 
Probably you added new items in wrong way. After add some list items you should use refresh() method on listview.

```
var li = document.createElement("li"),
      ul = document.querySelector(".ui-listview");

li.innerHTML = "new item";
ul.appendChild(li);

tau.widget.Listview(ul).refresh();
```

**Comment by pkaczmarczy** [comment]
Yes, You're right.
Refresh call is required to correctly add an item.
I will close this issue.
