### ISSUE TITLE
[wearable] Number picker cuts long values

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU#186]
![image](https://user-images.githubusercontent.com/18300603/60608292-6593a500-9dbf-11e9-98c7-ff6b92a19c39.png)
Problem Description:
In number picker, long values (more than 3 digits) are cut at the right side.

**Comment by TomaszLukawskiSam** [comment]
This issue was solved by path to another issue (https://github.com/Samsung/TAU/pull/210)

**Comment by korneliakobiela** [comment]
Looks good to me
