### ISSUE TITLE
Search input example not working

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#198]
1. Visit: https://code.tizen.org/demos?path=1.0%2Fexamples%2Fmobile%2FUIComponents%2Fcomponents%2Fcontrols%2Fsearchinput%2Findex.html
2. Enter some text
Observe:
displayed list is not changing

**Comment by pkaczmarczy** [comment]
The root cause of this issue is the same as here: https://github.com/Samsung/TAU-Design-Editor/issues/126

Widget does not work because active-page div has changed to "main" instead of "searchInputPage" - which causes listener registration to fail.

**Comment by korneliakobiela** [comment]
As I can see, this issue was solved by Samsung/TAU-Design-Editor/pull/147

**Comment by lslachciak** [comment]
I'll wait for code.tizen.org update to verify issue

**Comment by lslachciak** [comment]
works perfectly :ok_hand:
