### ISSUE TITLE
TAU UI Components: Group index doesn't work after select each dependent options

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#207]
[PRECONDITION]
Install TAU UI Components app version 5.0

[STEPS]
1. Open app

2. List > Selectable List

3. Click on checkbox of Group index 2 > uncheck Group index 2

4. Click all List Item > Obs

[OBSERVE]
Group Index doesn't check after select all dependent checkboxes.

[EXPECTED RESULT]
Group Index should be selected when all dependent checkboxes are selected, and GroupIndex should be deselect when not all of dependent checkboxes is unchecked.

**Comment by lslachciak** [comment]
works well
