### ISSUE TITLE
UIComponents: wearable - Text is cut on the list /Controls/Slider

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#211]
[STEP]
1. Open UI Components (wearable)
2. Controls
3. Slider
4. Scroll to last item

[OBSERVE]
text on last item "Extended with subtitle" is cut. 

[EXPECTED RESULT]
text should display normal

**Comment by lslachciak** [comment]
I reproduced issue with
link
https://code.tizen.org/demos?path=1.0%2Fexamples%2Fwearable%2FUIComponents%2Fcontents%2Fcontrols%2Fslider%2Findex.html

@TomaszLukawskiSam did you update gh-pages branc

**Comment by lslachciak** [comment]
works well
