### ISSUE TITLE
Button style -> circle in header is rectangle. 

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU#222]
## Description
- When the button with predefined styles (circle) is added to the application header, then a button shows as the rectangle.
## Steps to reproduce:
- Start a new project in WATT
- Mobile - Base Application
- Add Button to the application header
- Set attributes:
    - Style: circle
![image](https://user-images.githubusercontent.com/18300603/61470690-cc00f180-a981-11e9-9a83-9309ef0bf926.png)

**Comment by lslachciak** [comment]
@korneliakobiela is this TAU issue?

**Comment by korneliakobiela** [comment]
I think yes, because TAU is responsible for buttons style and look. But if you would like, I can transfer this issue to DE repository.

**Comment by TomaszLukawskiSam** [comment]
The PR with patch is ready to review.

Sample view:
![image](https://user-images.githubusercontent.com/29534410/62832445-6c1f0300-bc2e-11e9-8196-4e4a32268df1.png)
