### ISSUE TITLE
UIComponents: Button with icon in header is not visible

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#266]
UIComponents/components/headerfooter/header/lefticon.html

![image](https://user-images.githubusercontent.com/29534410/62281949-fc02c700-b44e-11e9-97fe-0042099088da.png)

**Comment by lslachciak** [comment]
@TomaszLukawskiSam could you share repro path?

**Comment by TomaszLukawskiSam** [comment]
The issue is not occurring in TAU 1.0

**Comment by lslachciak** [comment]
1.0 https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/headerfooter/header/lefticon.html
1.1 https://samsung.github.io/TAU/examples/1.1/examples/mobile/UIComponents/components/headerfooter/header/lefticon.html

**Comment by TomaszLukawskiSam** [comment]
The issue is caused by patches dedicated for DE. Purpose of the change was add feature to buttons to change icons and other properties in during life of widget. In short, this change was required for change button look without DE page reload.
