### ISSUE TITLE
Tabs: Tab underline seems too low

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#267]
UIComponents/components/navigationelements/tabs/tabs_with_title_2.html

![image](https://user-images.githubusercontent.com/29534410/62282257-85b29480-b44f-11e9-8848-dc94d4e52f5c.png)

**Comment by lslachciak** [comment]
reproduced on https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/navigationelements/tabs/tabs_with_title_2.html

**Comment by TomaszLukawskiSam** [comment]
The patch has already merged
