### ISSUE TITLE
IndexScrollbar: Scrollbar item and list position is different

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#268]
UIComponents/components/navigationelements/indexscrollbar.html

![image](https://user-images.githubusercontent.com/29534410/62282466-ec37b280-b44f-11e9-8ccd-5a40b93bc4a2.png)

**Comment by lslachciak** [comment]
@TomaszLukawskiSam  shouldn't we make PR to 1.0 also?

**Comment by TomaszLukawskiSam** [comment]
The patch has already merged to TAU 1.0
