### ISSUE TITLE
IndexScrollbar with search: wrong button size

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#269]
UIComponents/components/navigationelements/indexscrollbar_floating_button.html

![image](https://user-images.githubusercontent.com/29534410/62282584-1a1cf700-b450-11e9-8031-55bf1ff38823.png)

**Comment by lslachciak** [comment]
Not reproduced on 1.0 https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/navigationelements/indexscrollbar_floating_button.html

**Comment by TomaszLukawskiSam** [comment]
The issue is solved by patch for another issue (https://github.com/Samsung/TAU/pull/288).
