### ISSUE TITLE
Page Indicator & Page Indicator dotted looks the same

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#270]
http://localhost:8888/examples/mobile/UIComponents/components/navigationelements/pageindicator.html

![image](https://user-images.githubusercontent.com/29534410/62282729-5b150b80-b450-11e9-8d3e-4de36a504c70.png)

**Comment by lslachciak** [comment]
reproducible on 
https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/navigationelements/index.html

**Comment by TomaszLukawskiSam** [comment]
In previous version of Tizen, the TAU supported page indicator like "bars". 
![image](https://user-images.githubusercontent.com/29534410/62461783-fa563d80-b785-11e9-9fd2-9063217f0471.png)

We have to decide if unify page indicator to dots (remove one unnecessary page) or implement bars.

**Comment by pkaczmarczy** [comment]
Connected issue: https://github.com/Samsung/TAU/issues/176

**Comment by TomaszLukawskiSam** [comment]
The patch solved the issue.
