### ISSUE TITLE
Listview: Colored items texts are brightened after scroll

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#271]
UIComponents/components/list/liststyles.html

![image](https://user-images.githubusercontent.com/29534410/62282831-8e579a80-b450-11e9-8b3a-b9214c370de6.png)

UIComponents/components/list/normallist.html

![image](https://user-images.githubusercontent.com/29534410/62283090-1047c380-b451-11e9-89c2-b3c08f77b578.png)

**Comment by lslachciak** [comment]
reproducible on 1.0
https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/list/liststyles.html

**Comment by lslachciak** [comment]
please prepare PR with cherry pick for 1.0

**Comment by TomaszLukawskiSam** [comment]
The patch has already merged to TAU 1.0
