### ISSUE TITLE
Expandable List: After expanding list a back required twice press

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#273]
Url before list expand
`/UIComponents/components/list/expandable/expandable.html`

Url after list expand
`/UIComponents/components/list/expandable/expandable.html#`

**Comment by lslachciak** [comment]
In case of https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/list/expandable/expandable.html
url stays the same
but clicking back button in browser causes going back to previous page not collapsing list

**Comment by lslachciak** [comment]
In case of 1.0 behavior is different but also problematic (back button is not available)
https://samsung.github.io/TAU/examples/1.1/examples/mobile/UIComponents/components/list/expandable/expandable.html
