### ISSUE TITLE
Buttons: Icon on button is not centered

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#274]
mobile/UIComponents/components/controls/button/index.html

![image](https://user-images.githubusercontent.com/29534410/62283643-48033b00-b452-11e9-8f96-c37844a869a1.png)

**Comment by lslachciak** [comment]
reproduced on https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/controls/button/index.html

**Comment by TomaszLukawskiSam** [comment]
The patch has already merged
