### ISSUE TITLE
DropDownMenu: Press effect remains after select

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#275]
UIComponents/components/controls/dropdownmenu.html

![image](https://user-images.githubusercontent.com/29534410/62283851-c233bf80-b452-11e9-8338-d326eb262756.png)

**Comment by lslachciak** [comment]
Not reproducible on 1.0
https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/controls/dropdownmenu.html

**Comment by TomaszLukawskiSam** [comment]
The patch has already merged.

**Comment by lslachciak** [comment]
fixed
