### ISSUE TITLE
Search Input: Clear button is moved too much to right

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#276]
UIComponents/components/controls/searchinput/index.html

![image](https://user-images.githubusercontent.com/29534410/62284129-56058b80-b453-11e9-83da-37d555d69070.png)

**Comment by lslachciak** [comment]
Not reproducible on 1.0 https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/controls/searchbar/searchbar.html
