### ISSUE TITLE
Search Bar: Looks wrong & doesn't work

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#277]
UIComponents/components/controls/searchbar/searchbar.html

![image](https://user-images.githubusercontent.com/29534410/62284386-d0cea680-b453-11e9-9086-f89afbcb8b23.png)

UIComponents/components/controls/searchbar/searchbar-with-icon.html

![image](https://user-images.githubusercontent.com/29534410/62284456-ef34a200-b453-11e9-8804-a116e964bcb1.png)

**Comment by lslachciak** [comment]
Not reproducible on 1.0 https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/controls/searchbar/index.html

**Comment by TomaszLukawskiSam** [comment]
The issue is solved by patch for another issue (https://github.com/Samsung/TAU/pull/288).
