### ISSUE TITLE
Slider: Vertical doesn't work

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#278]
UIComponents/components/controls/slider.html

![image](https://user-images.githubusercontent.com/29534410/62284624-3cb10f00-b454-11e9-95a9-b2d79f10d99b.png)

**Comment by lslachciak** [comment]
not reproducible on 1.0
https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/controls/slider.html

**Comment by lslachciak** [comment]
reproduced on 1.1
https://samsung.github.io/TAU/examples/1.1/examples/mobile/UIComponents/components/controls/slider.html

**Comment by pkaczmarczy** [comment]
PR has been already merged.

**Comment by TomaszLukawskiSam** [comment]
The patch solved the issue.
