### ISSUE TITLE
MoreMenu: After popup open the first item is highlighted

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#279]
UIComponents/components/popup/moremenufooter.html#?popup=true

![image](https://user-images.githubusercontent.com/29534410/62284967-fd36f280-b454-11e9-9c97-9fcb98d7792b.png)

**Comment by lslachciak** [comment]
Not reproducible on 1.0 https://samsung.github.io/TAU/examples/1.0/examples/mobile/UIComponents/components/popup/moremenufooter.html#?popup=true

**Comment by lslachciak** [comment]
Reproducible on https://samsung.github.io/TAU/examples/1.1/examples/mobile/UIComponents/components/popup/moremenufooter.html#?popup=true

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
The patch has been already merged.

**Comment by lslachciak** [comment]
fixed
