### ISSUE TITLE
Snaplistview: Selected item has dimmed text

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#280]
wearable/UIComponents/contents/list/snaplistview_no_header.html

![image](https://user-images.githubusercontent.com/29534410/62286794-c2cf5480-b458-11e9-8111-af85ef471de1.png)

**Comment by lslachciak** [comment]
Reproduced on 1.0 too
https://samsung.github.io/TAU/examples/1.0/examples/wearable/UIComponents/

**Comment by pkaczmarczy** [comment]
PR has been already merged.

**Comment by TomaszLukawskiSam** [comment]
The issue has solved.
