### ISSUE TITLE
Processing: Small doesn't show

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#284]
UIComponents/contents/controls/processing/small_processing.html

![image](https://user-images.githubusercontent.com/29534410/62293011-ee0d7000-b467-11e9-819c-8e54f8726acc.png)

**Comment by lslachciak** [comment]
This is also 1.0 issure
https://samsung.github.io/TAU/examples/1.0/examples/wearable/UIComponents/

https://samsung.github.io/TAU/examples/1.1/examples/wearable/UIComponents/

**Comment by TomaszLukawskiSam** [comment]
Cause of the issue is evaluation inline js scripts loaded by XMLHttp request. When the same script is loading from file the issue is not occurring.

**Comment by TomaszLukawskiSam** [comment]
The patch has already merged.

**Comment by lslachciak** [comment]
fixed in 1.1
