### ISSUE TITLE
Processing: Full processing is cut at right side

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#285]
UIComponents/contents/controls/processing/full_processing.html

![image](https://user-images.githubusercontent.com/29534410/62293192-53f9f780-b468-11e9-9944-7244a03837f3.png)

Sending effect also is broken
UIComponents/contents/controls/processing/sending.html

**Comment by lslachciak** [comment]
I'm not able to reproduce this on https://samsung.github.io/TAU/examples/1.1/examples/wearable/UIComponents/contents/controls/processing/full_processing.html
(when going form UIComponents)

**Comment by TomaszLukawskiSam** [comment]
Issue still exists. Verified also on emulator 5.0

![image](https://user-images.githubusercontent.com/29534410/62438931-f6a4c580-b749-11e9-983d-b67577c9634b.png)

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
Hi, can you check the issue again? Thank You :)

**Comment by lslachciak** [comment]
Issue reproducible on emulator

**Comment by TomaszLukawskiSam** [comment]
The issue has solved.
