### ISSUE TITLE
Add dist.zip to published release

### ISSUE THREAD

**Issue by patuwwy** [Samsung/TAU#306]
As a programmer, I want to get the latest version. To get it, I need to download the entire repo (> 200 MB) or files from dist. It may be useful to add the dist- {version} .zip file when publishing a new release on GitHub.

**Comment by lslachciak** [comment]
I added dist.zip to the two latest releases:
https://github.com/Samsung/TAU/releases

**Comment by patuwwy** [comment]
Awesome! Thanks!
