### ISSUE TITLE
Arclistview: Highlight overlaps the scrollbar

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU#318]
Issue reproducible only on device.

**Comment by pkaczmarczy** [comment]
This issue is more complicated. I will switch to different problem for now.

**Comment by singa2000** [comment]
Is the issue  means like followings screenshot?
If so it's normal operation and it's same behavior with tizen native app.
![overwright](https://user-images.githubusercontent.com/31196177/72230529-7b4d1700-35f9-11ea-82e2-6a6dc6836291.png)

**Comment by lslachciak** [comment]
We think there are two issues:


1.
In Native apps after going to Settings -->apps options list
scrollbar is over highlight. In TAU app case highlight is over scrollbar (**light blue part is covered**)
You can see that light blue part of scrollbar is never covered in native app.

2.
In native app after finishing scrolling list, **scroll bar disappears  before showing highlight.**
In TAU apps **scroll bar disappears after showing highlight** so overlap occurs.

**Comment by TomaszLukawskiSam** [comment]
Patch for the issue has already been merged. The issue can be close.

**Comment by lslachciak** [comment]
works good
