### ISSUE TITLE
Verify replacement TAU.js by tau.bundle.js in apps

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#335]
Check possible issues.

- verification on devices (from Tizen 2.3.2 wearable)
- verification in sample apps
- performance tests
- (lower priority) ideas for performance improvement

**Comment by singa2000** [comment]
When it test, would you compare the launch performance, please?

**Comment by TomaszLukawskiSam** [comment]
Mobile profile:
 - Emulator (2.4)
  "TypeError: Type error " : tau.bundle.js:1

**Comment by pkaczmarczy** [comment]
I have started checking 3.0 wearable emulator (tizen-3.0-wearable_20171211.1 from Tizen Studio 3.3).

With TAU 1.1 and tau.js loaded Graph widget works correct.

After I have launched the app with tau.bundle.js I get the error:

```
W/ConsoleMessage( 3356): [pfNnUFu3sB] lib/tau/wearable/js/tau.bundle.js:1: Uncaught TypeError: Illegal invocation
```

**Comment by pkaczmarczy** [comment]
I have collected data about tau.js and tau.bundle js execution time on tizen 4.0 wearable emulator (from SDK).
Bundled file execution time takes much more time (about 800 - 900 ms) compared to normal tau.js file (about 220 - 250 ms). I attach the plot showing collected data:
![timing](https://user-images.githubusercontent.com/38784474/63264722-0ebd2e80-c28c-11e9-8689-966de6363548.png)
It should be noticed that on actual device this gap between those two version will grow up.

I also attach screens from timeline for both files:
tau.js:
![Screenshot from 2019-08-19 14-14-29](https://user-images.githubusercontent.com/38784474/63264794-3f04cd00-c28c-11e9-9e5d-5d23ea3d5252.png)

tau.bundle.js:
![Screenshot from 2019-08-19 14-13-10](https://user-images.githubusercontent.com/38784474/63264807-46c47180-c28c-11e9-9e26-1849bd05c06c.png)

**Comment by TomaszLukawskiSam** [comment]
Data collected for Emulator 4.0 mobile for bundle and not bundle TAU.

**tau.js**
time of script evaluation 104ms
![image](https://user-images.githubusercontent.com/29534410/63274516-33230600-c2a0-11e9-9d59-c150f27fec15.png)

**tau.bundle.js**
time of script evaluation 590ms
![image](https://user-images.githubusercontent.com/29534410/63274744-9f9e0500-c2a0-11e9-995c-034cce840e17.png)

| Version | tau.js | tau.bundle.js |
| ----------|---------|------------------|
| 2.4 (emulator) |  not started properly  |  "TypeError: Type error "  |
| 3.0 (emulator) |  app works good with exception of "Interactive 3D" - content doesn't show, no issues in console log  |  "Uncaught TypeError: Illegal invocation"  |
| 4.0 (emulator) |  works good  |  works good   |
| 5.0 (device) |  works good  |  works good   |

**Comment by TomaszLukawskiSam** [comment]
The feature of TAU bundle has prepared as specific for Design Editor requirement and as solution for all framework features in one file package. Above data shows that this solution is very time consuming. For better performance we should rather deliver for developers light version of framework instead of big package.
After analyzing applications that uses the TAU, one comes to the conclusion that developers usually only use part of the widgets.

**Comment by singa2000** [comment]
Thanks for your analysis.
How about the memory size?

**Comment by TomaszLukawskiSam** [comment]
Memory usage

**tau.bundle.js**
![image](https://user-images.githubusercontent.com/29534410/63316325-c7c44d00-c30e-11e9-99dc-1a2395f9b252.png)

**tau.js**
![image](https://user-images.githubusercontent.com/29534410/63316364-ede9ed00-c30e-11e9-9eda-7201f80d66e9.png)

| version | tau.js | tau.bundle.js | difference |
| - | - | - | - |
| emulator 4.0 | 3.9 MB - 6.8 MB | 9.5 MB - 15 MB | more min: 243% max: 220% |

**Comment by singa2000** [comment]
It's good.~
Thanks for your analysis.
We can be close it

**Comment by singa2000** [comment]
Would you check it again, please?
1. With TW1 device the difference in execution time is even bigger: ~1.5seconds vs 6-8 seconds.
   => Did you measure it by  you see on the screen?
         Would you check it again, please? It's too bigger.
2.  Would you check memory and launch performance by each external library, please?
3.  Would you consider  how to divide TAU by component like JQuery?
     Just for example, tau.js tau.i3d.js , tau.graph.js tau.coverflow.js ?

**Comment by TomaszLukawskiSam** [comment]
> Would you check it again, please?
> 
>     1. With TW1 device the difference in execution time is even bigger: ~1.5seconds vs 6-8 seconds.
>        => Did you measure it by  you see on the screen?
>        Would you check it again, please? It's too bigger.
> 
>     2. Would you check memory and launch performance by each external library, please?
> 
>     3. Would you consider  how to divide TAU by component like JQuery?
>        Just for example, tau.js tau.i3d.js , tau.graph.js tau.coverflow.js ?

I'll verify again and answer you.

**Comment by TomaszLukawskiSam** [comment]
Device TW1
Model=Tizen4/Unified;
Build=tizen-4.0-unified_20190412.1;
Release=20190412.1;
[Build]
Type=eng;
Date=20190412_023613;
Time=02:36:13;
Variant=NONE;
ID=tizen-4.0-unified;

![image](https://user-images.githubusercontent.com/29534410/63415071-69c26300-c3fd-11e9-92d6-1d8daa577687.png)

How data was collected:
- import UIComponents with tau.bundle.js as Tizen project
- install & launch
- open shell console
- run command > sdb shell
- run command > app_launcher -s pfNnUFu3sB.TAUUIComponents -w
... successfully launched pid = 7849 with debug 1 port: **45154** (port is veriable)
- open second shell console
- run command > sdb forward tcp:45154 tcp:**45154**
- open chrome browser
- open url: http://localhost:45154
- select "Timeline"
- press F5 to rerun app

**Comment by TomaszLukawskiSam** [comment]
**d3.min.js + tauCharts.min.js + jquery.js + r-type.min.js + tau.js**
![image](https://user-images.githubusercontent.com/29534410/63421027-28838080-c408-11e9-9a6c-5df0a01342dd.png)

| file | time |
| - | - |
| d3.min.js | 424ms |
| tauCharts.min.js | 1500ms |
| jquery.js | 310m |
| r-type.min.js | 1960ms |
| tau.js | 960ms |

**Comment by TomaszLukawskiSam** [comment]
> Would you check it again, please?
> 
>     1. With TW1 device the difference in execution time is even bigger: ~1.5seconds vs 6-8 seconds.
>        => Did you measure it by  you see on the screen?
>        Would you check it again, please? It's too bigger.
> 
>     2. Would you check memory and launch performance by each external library, please?
> 
>     3. Would you consider  how to divide TAU by component like JQuery?
>        Just for example, tau.js tau.i3d.js , tau.graph.js tau.coverflow.js ?

Point 1.
I think I confirmed ealier results.
During tests I saw how the app is showing on screen.

Point 2.
I prepared times of script evaluation for all libraries. In case of memory utilisation I have to prepare methodology.

Point 3.
At the moment all libraries are as separate files, eg. /UIComponents/contents/graphs/static_graph.html

**Comment by singa2000** [comment]
Would you also check the memory size each external library, please?

**Comment by TomaszLukawskiSam** [comment]
> Would you also check the memory size each external library, please?

Ok. It will take me a while.

**Comment by TomaszLukawskiSam** [comment]
> Would you also check the memory size each external library, please?

I updated my comment above (https://github.com/Samsung/TAU/issues/335#issuecomment-523382177)

**Comment by singa2000** [comment]
Thanks . We can close the issue.
