### ISSUE TITLE
ui-listview-divider breaks listview

### ISSUE THREAD

**Issue by martijnvankekem** [Samsung/TAU#342]
Both in the latest stable (1.0.3) as in the newest version (1.1.3), using an ui-listview-divider element inside a listview breaks the listview itself.

When scrolling, the item is not centered anymore because the extra scroll-space is not calculated. When inserting multiple ui-listview-divider elements, the scroll steps become so small you even have to scroll 5 times to go to the next item.

**Comment by TomaszLukawskiSam** [comment]
I've reproduced the issue. Now I try to resolve the issue.

**Comment by TomaszLukawskiSam** [comment]
The issue is caused by bug in submodule for scrolling. The scrolling tool assumes that all list items have the same height as first child element - this is wrong assumption and needs fix.
The fix will be to define snap points for the list items. The widget API will not change.

**Comment by TomaszLukawskiSam** [comment]
@martijnvankekem 
Hi, the hotfix is almost done. I have only one small suggestion to the app.
When snaplistview has list devider as first item then header should be have class `ui-header-smaller` because divider takes some space.
In other case when you use snaplistview you should add `ui-header-big`.

**Comment by lslachciak** [comment]
@martijnvankekem  issue was fixed in TAU 1.0.7 
https://github.com/Samsung/TAU/releases/tag/1.0.7

Could you close issue if the fix is OK for you?

**Comment by martijnvankekem** [comment]
Great, thank you!
