### ISSUE TITLE
Change output filenames and path

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#358]
Files which should be in output
tau.js
tau.graph.js
tau.i3d.js
tau.coverflow.js

Also try to make path like
dist/common/js/tau.graphs.js
simpler (shorter)

**Comment by pkaczmarczy** [comment]
I have few propositions to put those files:
1) 
```
dist/common/tau.coverflow.js
dist/common/tau.graph.js
dist/common/tau.i3d.js
```
2)
```
dist/external/tau.coverflow.js
dist/external/tau.graph.js
dist/external/tau.i3d.js
```
3) 
```
dist/libs/tau.coverflow.js
dist/libs/tau.graph.js
dist/libs/tau.i3d.js

Currently under dist/libs there are original third party libraries source files. In this case I would remove them and leave only bundled files.
```

Dear @lslachciak  Could you please share your opinion which suits the best?
Personally i like the third option the most.

**Comment by lslachciak** [comment]
@pkaczmarczy personally I like libs folder idea

**Comment by pkaczmarczy** [comment]
I have prepared the PR: https://github.com/Samsung/TAU/pull/374

**Comment by pkaczmarczy** [comment]
PR has been already merged.

**Comment by lslachciak** [comment]
Follow up issue: 
https://github.com/Samsung/TAU-Design-Editor/issues/328
