### ISSUE TITLE
SnapList: Newly added items cannot be selected

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU#366]
New items after refresh take correct syling, but they cannot be selected

**Comment by pkaczmarczy** [comment]
This issue is caused by incorrect scrollable height calculation during refresh.
This should be recalculated during refresh function. This is a quite complicated task when listview is already built because some elemens are changing its dimensions (scaling to show hide effect)

**Comment by lslachciak** [comment]
I'll close this issue after getting confirmation that it is working well
