### ISSUE TITLE
TAU Online examples throw 404 not found

### ISSUE THREAD

**Issue by martijnvankekem** [Samsung/TAU#380]
Visiting the TAU examples like https://samsung.github.io/TAU/examples/wearable/UIComponents/index.html, throw a 404 error since a couple of weeks.

**Comment by lslachciak** [comment]
@martijnvankekem 
we didn't know that anyone is using this url :)
This was changed recently for performance reasons of code.tizen.org

Officially you can use access examples from
1. Documentation sites e.g
https://docs.tizen.org/application/web/api/5.0/ui_fw_api/Mobile_UIComponents/mobile_Button.htm
--> use "use example" button
2. Using direct url:
https://code.tizen.org/TAU/1.0/examples/mobile/UIComponents/

Please note that TAU examples are synced periodically, not for every pre-release.
You can check current version using this url
https://code.tizen.org/TAU/1.0/examples/mobile/UIComponents/lib/tau/mobile/js/tau.js

I'll update main TAU site https://samsung.github.io/TAU/ with for proper urls

**Comment by lslachciak** [comment]
@martijnvankekem now site https://samsung.github.io/TAU/ contains proper links to TAU examples
e.g. https://code.tizen.org/TAU/1.0/examples/mobile/UIComponents/

**Comment by martijnvankekem** [comment]
Great, thanks!
