### ISSUE TITLE
NumberPicker: auto-created 'Set' button not destroyed when calling destroy()

### ISSUE THREAD

**Issue by martijnvankekem** [Samsung/TAU#387]
When calling the `destroy()` method of a NumberPicker, the auto-created 'Set' button does get its class `ui-number-picker-set` removed, but the element itself stays in place.

This goes wrong when executing these steps:

1. A page is called by `tau.changePage("#page");`
2. The NumberPicker is created
3. An other page is called by `tau.changePage("#otherPage");` and thus the `NumberPicker.destroy()` gets called.
4. The page is called again by `tau.changePage("#page");`
5. The NumberPicker is created again, with another new button, so now there are 2 buttons visible.

**Comment by TomaszLukawskiSam** [comment]
The patch has already been merged.
