### ISSUE TITLE
SnapListview: scroll position not resetted when switching pages

### ISSUE THREAD

**Issue by martijnvankekem** [Samsung/TAU#388]
**Seems to be working in 2.1.4, not in 2.0.8**

When creating a listview, and then switching to another page and after that returning to that same page, all by using the `tau.changePage()` method, the maximum scroll amount is limited by the item you've got currently selected.

Example:
A listview has 3 items, when the 3rd item is active and `tau.changePage()` is called, after returning to that page later, the first item is selected again, but you can't scroll down any further. You have to scroll 3 times UP, in order to scroll 3 times DOWN again.

Another example:
A listview has 3 items, when the 2nd item is active and `tau.changePage()` is called, after returning to that page later, the first item is selected again, but you can only scroll down 1 more item (because 2 + 1 = 3). If you scroll UP 2 times, you can scroll down 3 times again.

**This happens no matter if you destroy the SnapListView or not!**

Expected: after returning to the page and the first item is selected again, the scroll index should also be reset to zero and you should be able to scroll down all the way to the bottom again.

**Comment by lslachciak** [comment]
@martijnvankekem I think https://github.com/Samsung/TAU/commit/6c22539c1d6a7bca3ce622c8926007b17fdf5537
which was released with TAU 1.0.9 and exists in TAU 1.0.10 fixes your issue.
Could you confirm?
