### ISSUE TITLE
Progress element cannot be selected in Design Area

### ISSUE THREAD

**Issue by korneliakobiela** [Samsung/TAU#397]
## Technical
Profile: Mobile
## Description
User cannot select added progress element in the Design Area. Only the structure view is available then.
## Steps to reproduce
1. Create a new project in Design Editor
2. Add progress element
3. Save the file
4. Close and Reopen DE (until Samsung/TAU-Design-Editor#368 is done).
5. Try to select progress element clicking on it

## Expected behaviour
The progress element is selected.
## Actual behaviour
Content element is selected.

**Comment by pkaczmarczy** [comment]
@korneliakobiela Could you please check this issue, I think it has been already fixed.

**Comment by lslachciak** [comment]
@korneliakobiela please reopen issue if problem occurs
Approriate PR was merged

**Comment by korneliakobiela** [comment]
It's ok, the problem doesn't exist.
