### ISSUE TITLE
dist folder unneded

### ISSUE THREAD

**Issue by lslachciak** [Samsung/TAU#4]
In tau_4.0 branch dist folder with compiled TAU is unneeded.
TAU releases already contain compiled TAU https://github.com/Samsung/TAU/releases

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
The TAU on branch tizen_4.0 has been updated. The `dist` folder has been removed.

**Comment by lslachciak** [comment]
I confirm, dist folder not longer exists.
