### ISSUE TITLE
Date Picker - day indicator is overlapped

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU#405]
![Screenshot from 2019-09-25 14-37-15](https://user-images.githubusercontent.com/38784474/65601236-fd112a00-dfa1-11e9-9ee1-4a7e3e58543a.png)

Day indicator is hidden under "Set" button

**Comment by TomaszLukawskiSam** [comment]
The patch has already been merged.

**Comment by pkaczmarczy** [comment]
The issue has been fixed.
