### ISSUE TITLE
Prepare Graph documentation for Tizen docs

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#454]
Basing on the Coverflow examples
https://docs.stg.tizen.org/staging/848/application/web/api/latest/ui_fw_api/Mobile_UIComponents/mobile_Coverflow.htm
https://docs.stg.tizen.org/staging/848/application/web/api/latest/ui_fw_api/Wearable_UIComponents/wearable_Coverflow.htm
PR: https://github.com/Samsung/tizen-docs/pull/848
prepare mobile and wearable documentation for graph

**Graph** documentation should be **part of  Extended Mobile UI Components and Extended Wearable UI Components respectively.**

https://docs.stg.tizen.org/staging/848/application/web/api/latest/ui_fw_api/Wearable_UIComponents/wearable_extended_component_list.htm

https://docs.stg.tizen.org/staging/848/application/web/api/latest/ui_fw_api/Mobile_UIComponents/mobile_extended_component_list.htm

repo: tizen-docs
branch: tizen_5.5_prepare

**Comment by TomaszLukawskiSam** [comment]
The PR has already been merged.
