### ISSUE TITLE
 Prepare Dimmer documentation for Tizen docs

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#455]
Basing on the Coverflow examples
https://docs.stg.tizen.org/staging/848/application/web/api/latest/ui_fw_api/Mobile_UIComponents/mobile_Coverflow.htm
https://docs.stg.tizen.org/staging/848/application/web/api/latest/ui_fw_api/Wearable_UIComponents/wearable_Coverflow.htm
PR: Samsung/tizen-docs#848
prepare mobile and wearable documentation for dimmer

**Dimmer** documentation should be **part of Mobile UI Components and Wearable UI Components** respectively.

https://docs.stg.tizen.org/staging/848/application/web/api/latest/ui_fw_api/Wearable_UIComponents/wearable_component_list.htm

https://docs.stg.tizen.org/staging/848/application/web/api/latest/ui_fw_api/Mobile_UIComponents/mobile_extended_component_list.htm

repo: tizen-docs
branch: tizen_5.5_prepare

**Comment by singa2000** [comment]
To avoid confusion,
The dimmer widget don't need the extended library. It's basic component.

So  it's  not
https://docs.stg.tizen.org/staging/848/application/web/api/latest/ui_fw_api/Mobile_UIComponents/mobile_extended_component_list.htm 

It's correct the
https://docs.stg.tizen.org/staging/848/application/web/api/latest/ui_fw_api/Mobile_UIComponents/mobile_component_list.htm

**Comment by pkaczmarczy** [comment]
I have prepared a commit:
https://github.com/pkaczmarczy/tizen-docs/tree/add-dimmer-documentation

But I cannot see any previous changes (adding images, examples formatting in 5.5 directory, maybe we should update this docs before changing anything else?) @lslachciak what do you think? It looks like changes from 5.0 version (its a different directory are not available in 5.5).

**Comment by lslachciak** [comment]
@pkaczmarczy I agree. If we are missing any changes form 5.0 documentation we should update it.
I added this task on our todo list
https://github.com/Samsung/TAU/issues/457

**Comment by pkaczmarczy** [comment]
PR: https://github.com/Samsung/tizen-docs/pull/895

**Comment by pkaczmarczy** [comment]
PR has been already merged.

**Comment by singa2000** [comment]
PR was merged and we can close it.
