### ISSUE TITLE
install issues on win10 

### ISSUE THREAD

**Issue by orcema** [Samsung/TAU#463]
I followed the install instructions on the readme file but installation fails on my laptop having win10 as OS, node version v8.11.4 and npm 6.12.0.

The 1st issue happens with the instruction  "npm install". I get the error message:

> "node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v1.0.1/node-v57-win32-x64.tar.gz"

I already once removed the folder "node_modules", removed the file package-lock.json inside the TAU folder and finally did a "npm install npm@latest -g" but i still get that error.

I thought let's try to go further with the instruction "npx grunt build" and all seems to work well and i got the message
> Done, without errors"

Next instruction "npx grunt test" fails with the message
> Running "qunit:main-wearable" (qunit) task
Testing tests/js/core/core/core.html Warning: Cannot read property 'connected' of undefined Use --force to continue.
Aborted due to warnings.

Then a installed the http-server and launched it with the command
> npx http-server -p 8888 -a localhost

and was able to navigate to 
> http://localhost:8888/examples/wearable/UIComponents/

but page didn't show up due to too many redirects. I solved this issue by extending the url to 
> http://localhost:8888/examples/wearable/UIComponents/index.html

![image](https://user-images.githubusercontent.com/12600222/67751401-57822800-fa31-11e9-992c-d736e8cb12a3.png)

the web console revealed some files could not be fetched
![image](https://user-images.githubusercontent.com/12600222/67751509-88faf380-fa31-11e9-8d81-02451698bed7.png)

and indeed there is no tau library in the target folder
![image](https://user-images.githubusercontent.com/12600222/67751668-d24b4300-fa31-11e9-894c-859544cdb635.png)

Did someone else had this kinds of issues or can someone please help me identifying what I'am doing wrong ?

**Comment by lslachciak** [comment]
@orcema I think your issue on Windows is connected with symbolic links
please note that 
mobile/theme/default
and 
werable/theme/default 
are Linux symbolic links to changeable folder which are not recognisable on Windows
please try to copy appropriate content to it

**Comment by lslachciak** [comment]
@orcema did you check symbolic links comment?
please reopen issue if more help needed
