### ISSUE TITLE
Section changer issue when fillContent: false

### ISSUE THREAD

**Issue by smozhaykin** [Samsung/TAU#464]
Please, check the following gist: https://gist.run/?id=238a62489fcb56f42aa395bfe401d3a2 (tau version is 1.0.15)

Currently when scrolling with mouse wheel in browser (or using bezel on watch), after item 4  (or before item 5) empty space is displayed. When `fillContent: true` this is not visually observed, because only one item is displayed on the screen.

Another observation: when dragging empty space is displayed, but after releasing mouse item appears. AFAIK because of `_repositionSections` is called on `transitionEnd` event. I think that behavior should be consistent and no empty space should be displayed for scrolling.

Ideally empty space shouldn't be displayed even while dragging (before releasing mouse)

**Comment by lslachciak** [comment]
I can't see empty space when fillContent is set to false.
I have question, would it be better for you to use spin widget instead in your case? (e.g. availavble in TAU 1.0.22)
https://github.com/Samsung/TAU/commit/1c5b30348e7f1350cdd42d4255b97069a90e721d

**Comment by lslachciak** [comment]
@smozhaykin if spinner widget is not satisfying solution for your case, please reopen this issue
