### ISSUE TITLE
SnapListview: Cannot build widget with one or none items

### ISSUE THREAD

**Issue by pkaczmarczy** [Samsung/TAU#477]
Exception is thrown as below:
![Screenshot from 2019-11-14 11-59-07](https://user-images.githubusercontent.com/38784474/68851499-5bbb7000-06d6-11ea-9eb4-c15b4e8e4f55.png)

Issue probably exists on 1.0 too, but I did not checked it.

**Comment by martijnvankekem** [comment]
I can confirm that this bug is also present in TAU 1.0.20.

**Comment by lslachciak** [comment]
@HunseopJeong could you merge PR https://github.com/Samsung/TAU/pull/540 if ready and close the issue?

**Comment by HunseopJeong** [comment]
Merged the PR(#540) for this issue.
