### ISSUE TITLE
Marquee: EndToEnd animation has blank moment

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#490]
In EndToEnd animation there is a blank moment

![image](https://user-images.githubusercontent.com/2246331/69537674-e9257c80-0f80-11ea-8dc9-9845cd15ee98.png)

![image](https://user-images.githubusercontent.com/2246331/69537739-05c1b480-0f81-11ea-9d7f-850d9f8fe635.png)

Beginning of the text should be visible together with the end of text

Reproduction:
1. visit: https://docs.tizen.org/application/web/api/5.0/ui_fw_api/Wearable_UIComponents/wearable_marquee.htm
2. click "use example"
3. put below sample code in app:
replace sample style for marquee to **endToEnd**

click Live Preview Button

**Comment by singa2000** [comment]
It fixed by https://github.com/Samsung/TAU/pull/525
@lslachciak 
Would you confirm the issue was fixed?

**Comment by lslachciak** [comment]
yes this issue was fixed in TAU 1.0.22
but samples on the code.tizen.org should be updated
