### ISSUE TITLE
[UI Component] Inconsistent behaviour of Time Picker vs. Date Picker

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#546]
[ How to reproduce]

UI Component App -> Controls -> Time Picker 24H -> nothing is selected

UI Component App -> Controls -> Date Picker -> month is selected

[ Problem]

Inconsistent behaviour between Time Picker and Date Picker.

Nothing should be selected in Date Picker or "Hrs" should be selected in Time Picker.

**Comment by lslachciak** [comment]
Issue fixed
