### ISSUE TITLE
SnapListView + rotary scrolling - wrong selection position

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#561]
Reproduction steps:
1. Latest TAU (not release)
2. Go to UIComponents -->List -->SnapListView
3. Rotary scroll with bezel (not touch)
Observe:
Selection gets higher and higher
Expected: Selection stays in the middle

**Comment by TomaszLukawskiSam** [comment]
The patch has already been merged. We can close the issue.

**Comment by lslachciak** [comment]
works good
