### ISSUE TITLE
ArcListView - wrong selection before entering menu item

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#566]
[wrong_selection.zip](https://github.com/Samsung/TAU/files/4116116/wrong_selection.zip)
Reproduction:
UIComponents --> List ->ArcListView -->ArcListView
start scrolling  + Long Tap (don' release finger)
Observe:
Wrong selection visible (see attached video)
Expected:
No selection or correct selection

**Comment by lslachciak** [comment]
This is reproducible also in other cases, but the long tap has easiest reproduction steps.

**Comment by grzegorz-czajkowski** [comment]
Selection is shown even if scroll is stopped by touch start. Selection should be shown when:
 * animation finished (not stopped by any touch events) or
 * touch end (if stopped by touch start while scrolling).

**Comment by grzegorz-czajkowski** [comment]
Patch merged, issue can be closed.
