### ISSUE TITLE
ArcListView - no marquee animation after second selection

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#567]
1. UIComponents -> List -> ArcListView -> ArcListView short
2. Scroll to second item
3. Scrol to first item
4. Scroll to second item
Observe:
No marquee animation. See attached video
[ArcListView - no marquee.zip](https://github.com/Samsung/TAU/files/4121251/ArcListView.-.no.marquee.zip)

Expected:
Marquee animation occurs once

**Comment by lslachciak** [comment]
[ArcListView - no marquee.zip](https://github.com/Samsung/TAU/files/4121245/ArcListView.-.no.marquee.zip)

**Comment by grzegorz-czajkowski** [comment]
In Second animation, text width is equal to container width and there is no need to perform animation. Looks like we need to re-recostruct marquee tree after carousel update.

**Comment by grzegorz-czajkowski** [comment]
Wrong width is applied at the beginning of *first* animation (there is no need to change item).
Applying ui-marquee directly to element style and reassigning from arc-list-view mechanism of applying marquee (_wrapTextContent) shows no issue suggesting that this is not issue with marguee itself but rather of  arc-list-view.

arc-list-view add "ui-marquee" to wrapped container but it is removed by framework in

`
			function render(stateObject, element, isChild) {
				var recalculate = false;

				if (stateObject.classList !== undefined) {
					slice.call(element.classList).forEach(function renderRemoveClassList(className) {
						if (!stateObject.classList.has(className)) {
							element.classList.remove(className);
							recalculate = true;
						}
					});
`

**Comment by grzegorz-czajkowski** [comment]
ui-marque is being removed since it is not added to stateDom.classList object.
I found that the following line in BaseWidget.js does not copy required classes:

`                        classList.add.apply(classList, slice.call(element.classList));`

Copying them in old js way solves this issue.
Requires more checks and tests.

**Comment by grzegorz-czajkowski** [comment]
Patches merged. Issue was in BaseWidget implementation. Fix may affects all TAU widgets.
