### ISSUE TITLE
1.Navigation Elements - Fast scroll

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#624]
Implement 
1.Navigation Elements - Fast scroll
according to the guidelines

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
We have already implemented ScrollHandler widget in mobile profile. The ScrollHandler has very similar behavior to FastScroll. I'll check possibility to join this widget to wearable profile.

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged.
