### ISSUE TITLE
[UIComponents] Marquee List - artifact

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#636]
List-->Marquee List 
Observe:
strange artifact:
![image](https://user-images.githubusercontent.com/2246331/74343044-b5e9d100-4daa-11ea-8c3b-1b229e1d3ca8.png)

**Comment by lslachciak** [comment]
This is not regression

**Comment by lslachciak** [comment]
looks like this example was done intentionally

**Comment by lslachciak** [comment]
tau v1.0.1 - no issue
tau v1.0.20 - issue

**Comment by lslachciak** [comment]
tau v1.0.10 - issue

**Comment by lslachciak** [comment]
tau 1.0.5 - issue
tau 1.0.2 - no issue
tau 1.0.3 - no issue
tau 1.0.4 - no issue

**Comment by lslachciak** [comment]
This is a regression after a3ca8365200f6c9215712f71f7da50c4c8af3cbb
