### ISSUE TITLE
Wearable Section Changer - Circular:true issue

### ISSUE THREAD

**Issue by DevronB** [Samsung/TAU#659]
When using the sectionchanger on wearable with the circular:true option there is a scroll/animation issue. The issue seems to occur when scrolling to section one after the start index ('ui-section-active'). When you scroll to the end/start of the sections it correctly scrolls to the start/end in a circular motion. But when you hit the second section after the start (initial 'ui-section-active') it seems to scroll all sections end to end to return at the section you had intended to scroll to. So the behaviour is correct, but the animation is very odd and not smooth.

**Comment by lslachciak** [comment]
@DevronB does the issue occurs only when rotating with bezel and no issue when swipe with finger?
I can see some strange behaviour on tau_1.0 in UIComponents sample app: Navigation-->Sectionchanger-->Circular + rotate with bezel

**Comment by lslachciak** [comment]
in problematic case

translate = "translate3d(" + x + "px," + y + "px, 0)";
is always called with x set to 0 in TAU

this is because 
calculateCustomLayout returns 360
I think there is something wrong with index calculation in this function

**Comment by DevronB** [comment]
Correct, I have confirmed in my case also this only occurs when using the bezel, not finger swipe.

**Comment by lslachciak** [comment]
Thank you @DevronB for confirmation.

After further investigaion I can say that the problem is with
_endScroll: function () 
```
				_endScroll: function () {
					console.log("this.scrolled: " + this.scrolled + " this.scrollCanceled: " + this.scrollCanceled);
					if (!this.enabled || !this.scrolled || this.scrollCanceled) {
						return;
					}

					this._repositionSections();
					this._super();
				},

```
In case of swipe this.scrolled is always true so this._repositionSections(); is called
In case of rotarydetend this.scrolled is false so this._repositionSections(); is not called

If I ommit 
`					if (!this.enabled || !this.scrolled || this.scrollCanceled) {`
condition there is no issue with section change animation

**Comment by DevronB** [comment]
Great, thank you. So is removing this code the solution, or does this.scrolled need to be set during rotarydetent event chain? Anyway when do you think a commit will be done to fix this issue?

Thank you for the fast diagnosis.

**Comment by lslachciak** [comment]
@DevronB fix for this issue has just been merged.
We plan to make new TAU release this week.

**Comment by DevronB** [comment]
Great, thank you. I pulled the commit and it seems to be working fine now.

**Comment by lslachciak** [comment]
TAU v1.0.27 released with fix for the issue
https://github.com/Samsung/TAU/releases/tag/v1.0.27

**Comment by DevronB** [comment]
I think there is still a small issue with this. When first using a section changer and setting the initial index to not 0, says setting ui-section-active to index 3 of 6. When you scroll via finger to the previous section(2) and back (3) it animates the sections end to end as per the issue. When you navigate via the bezel to the previous section(2) it also has the same behaviour. But scrolled a few sections the issue goes away.

**Comment by DevronB** [comment]
FYI, this is possibly only an issue if there is no default 'ui-section-active' class and the active section is set in js via setActiveSection.

**Comment by lslachciak** [comment]
Yes, I can observe some unexpected behaviour when ui-section-active is not set.
By default ui-section-active is set to 0 index. When API used some unexpected behaviours may occur.

**Comment by lslachciak** [comment]
In my tests
calling:

sectionChanger.setActiveSection(2, 0, true);
sectionChanger._repositionSections(true);

eliminated some issues, but this private API, so this is not recommended solution.

**Comment by DevronB** [comment]
Thanks, For the moment I've set the ui-section-active class but I have some scenarios where the start index is dynamic. I've also found that there is odd animation when fast scrolling with the Bezel. At certain points the animation goes backward (opposite direction). I'm thinking it's also related to the original issue.

**Comment by lslachciak** [comment]
@DevronB I made PR https://github.com/Samsung/TAU/pull/687 which fixes issue which I was able to reproduce
1. don't set ui-section-active
2. call sectionChanger.setActiveSection(2) in app
3. swipe left
4. observe

**Comment by DevronB** [comment]
Great. Did you happen to try the fast scrolling with the bezel issue? or could you not reproduce this? Thanks again for all your great work on this library!

**Comment by lslachciak** [comment]
@DevronB I didn't reproduce issue which you mention.
Could you confirm if PR #687 fixes your issue (at least with swipe)?

**Comment by DevronB** [comment]
This all seems to be working now I've but I have updated to TAU_1.2. I didn't get a chance to check in TAU_1.0 sorry. Thanks for your work.
