### ISSUE TITLE
Arclistview finger scrolling

### ISSUE THREAD

**Issue by DevronB** [Samsung/TAU#673]
Hi,

I'm using the Arclistview in my project. Generally it works very well when using the bezel but there is a a finger scroll issue that I have found. When the user scrolls up/down in the list with their finger it's sometime difficult to get the list to stay on the required item, after scrolling and the finger is lifted the list will try to centre on the closest item, but it regularly skips an item and goes too far. This makes the list difficult to navigate with the finger. Native lists don't have this behaviour and are much easier to navigate with the finger.

**Comment by lslachciak** [comment]
@DevronB we have some inertia implemented for ArcListView, so it will not stop immediatelly after finger up. And as I understand too big inertia on list is your problem.

Could you point out list examples in UIComponent app which has too big inertia in your opinion (or give us your sample) and let us know with which native app we should compare e.g. some Settings menu? Now I'm checking Native app Settings-> Advanced and I also see there some inertia on list.

**Comment by DevronB** [comment]
Yes I believe maybe the inertia is too sensitive or something on the Arclistview, it makes it difficult to navigate with the finger. I've made a couple of videos for comparison, I hope you can see?. Also on the Arclistview with lots of scrolling the animations sometimes become clunky and list items get a little skewed. If you use the TAU UIComponents sample with longer list you should see it too. The amimation is not always smooth.

OK, it won't let me attach videos, I will email them directly to you.

Thanks

**Comment by lslachciak** [comment]
@DevronB you can pack videos to zip and attach them here.

**Comment by DevronB** [comment]
I emailed you a one drive share link to download, I didn't see the gz format before but they're too big anyhow...

**Comment by lslachciak** [comment]
Ok, I saw videos.
I can see some strange lagging and unexpected moves in a very specific situation. Although problem is quite complicated.

**Comment by DevronB** [comment]
Thanks, I've had several users comment on the difficulty navigating and the fact the there is not scroll end vibration.

**Comment by DevronB** [comment]
I'm still getting feedback from users on the Arclistview scrolling being lagy and difficult to select items. It's far from the native list selections smoothness and behaviour. Can there be some focus put on this please as it makes my app seem very 'unprofessional'.

I've attached a recent video posted to me by a user of my app
[received_919119501873164.zip](https://github.com/Samsung/TAU/files/4639415/received_919119501873164.zip)

.

**Comment by DevronB** [comment]
Any comment/update on this? 

Although the Arclistview is nice, it's implementation could be smoother and more in line with the native controls. It's really the main issue I have with the UI professionalism of my app. It's the most used control as far as i'm concerned. Has this been improved in the newer TAU versions. Are you expecting it to run smoother on newer hardware? 

Also, is there a way/control to create a standard list without the 'Arc' behaviour like the next Bixby update has? see attached.
![Screen_20200626_093159](https://user-images.githubusercontent.com/27395345/85807245-7687b400-b790-11ea-8bf7-ea961889fa15.png)

**Comment by lslachciak** [comment]
Dear @DevronB 

TAU 1.2 version on which we are currently working on has a lot of improvements for lists adjusting them to latest UI.
I can not guarantee that we can satisfy all your cases, but we changed lists view a lot.
You can see some latest examples in UIComponents app
https://samsung.github.io/TAU/examples/1.2/examples/wearable/UIComponents/contents/presentation-views/list/index.html
(I recommend to view it in developer view in web browser with custom device size - 360x360)
