### ISSUE TITLE
Navigation Elements - Title Bar - Focused

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#678]
Navigation Elements - Title Bar - Focused

(old Presentation Views)

**Comment by TomaszLukawskiSam** [comment]
There are several task to do:
- adding possibility to overscroll listview to bottom `done`
- scrolling title to the center of screen `done`
- (optional) check older version of listview (snaplistview) as backward compatibility
- adding listview overscroll by bezel `in progress`
- changing size of title at the center position (scale during scroll) `done`
- examples `done`

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged.
