### ISSUE TITLE
User input elements -> Checkbox

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#700]
User input elements -> Checkbox

**Comment by grzegorz-czajkowski** [comment]
@singa2000 are you working on this? If not I can take care of this.

**Comment by singa2000** [comment]
oh.. No, I'm checking another issue.
Would you take care of this, please?
Thanks.

**Comment by grzegorz-czajkowski** [comment]
@lslachciak  Checkbox and Checkbox Small were updated according to guide. Howvere one example missing. Should we close this bug?

**Comment by lslachciak** [comment]
I think we can close
