### ISSUE TITLE
User input elements -> Radio

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#702]
wrong stylin
wrong example

**Comment by korneliakobiela** [comment]
New radio button styling is similar to the old one but differs in a few aspects:
1. Remove inner dots from inactive elements. (DONE)
2. Make lines thinner
3. Change colours.
4. Make dots bigger
5. Change the size of all elements.

**Comment by korneliakobiela** [comment]
Done things in the past two days: 
1. Thinner lines in Radio Buttons
2. Bigger dots inside the active one (edit graphic file)
3. Changing colours according to documentation.

Todo:
Change Example location

@lslachciak, should I prepare the new example as it looks in docs?

**Comment by korneliakobiela** [comment]
PR #797

**Comment by korneliakobiela** [comment]
All PR merged, please review it

**Comment by lslachciak** [comment]
works fine, closing issue
