### ISSUE TITLE
User input elements -> Slider

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#704]
wrong styling

**Comment by lslachciak** [comment]
@korneliakobiela please share status

**Comment by korneliakobiela** [comment]
I made a slider thinner according to documentation. I can't find where is the code for active dot (the one on the end of the slider with transparency). I can see that element bigger in docs.

**Comment by korneliakobiela** [comment]
PR is merged, please review changes

**Comment by lslachciak** [comment]
@korneliakobiela I see one more PR for this issue. I'll review/close after merging it

**Comment by korneliakobiela** [comment]
@lslachciak I referenced this PR by mistake. Sorry for the confusion :open_hands:
I corrected it in PR description but it didn't disappear here as a mention.

**Comment by lslachciak** [comment]
@korneliakobiela slider looks and works great :grin:
but together with styling change we also update examples so in order to close completely
User input elements -> Slider item
please place Slider example under User Input Elements --> Slider menu

**Comment by korneliakobiela** [comment]
Ok, I made PR with changes in examples

**Comment by korneliakobiela** [comment]
PR merged

**Comment by lslachciak** [comment]
Thank you @korneliakobiela 
works fine
