### ISSUE TITLE
Appbar --> Navigate up buttom

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#714]
Navigate up button not visible in example
header and Footer --> Simple title with back

**Comment by grzegorz-czajkowski** [comment]
Button is implemented according to guide and it's resotred to examples.
However, after click on it nothing happens. I created separate issue for this since this requires changes on router side - https://github.com/Samsung/TAU/issues/753.

**Comment by lslachciak** [comment]
ok, works fine
