### ISSUE TITLE
Buttons -> Flat button

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#719]
1. Verify styles
2. Update examples

**Comment by lslachciak** [comment]
@TomaszLukawskiSam is this issue complete, if not what we need to do here?

**Comment by TomaszLukawskiSam** [comment]
Patch has been already merged. The issue can be close.

**Comment by lslachciak** [comment]
Some remarks: 
1. Button example should be in Buttons -> Flat Button section of UI Component app
not Controllers
2. Examples text doesn't correspond to the text in Guideline exampple
3. In the Guideline there is 8px Left Margin between list entry and button I can't see this in debugger. Only see 16px padding
4. Right Margin for list entry seems to be 20px guide says about 24

@TomaszLukawskiSam could you check my remarks?

**Comment by TomaszLukawskiSam** [comment]
> Some remarks:
> 
>     1. Button example should be in Buttons -> Flat Button section of UI Component app
>        not Controllers
Done


>     2. Examples text doesn't correspond to the text in Guideline example
Examples in guideline has mixed buttons with style flat and contained on one screen. This may make confusion when user want to check example only flat button.
 
>     3. In the Guideline there is 8px Left Margin between list entry and button I can't see this in debugger. Only see 16px padding
>     4. Right Margin for list entry seems to be 20px guide says about 24

I think this margin has apply only for buttons on list.

**Comment by lslachciak** [comment]
We need to update margins in this issue, we did similar margin adjustment for list in
https://github.com/Samsung/TAU/pull/747/commits/1d1fcad18e2f384b0b05e4e07223afcc8c717896

**Comment by TomaszLukawskiSam** [comment]
Patches have been merged. Can we close the issue?

**Comment by lslachciak** [comment]
ok, seems fine
