### ISSUE TITLE
Presentation View -> List

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#729]
header color needs update
    check proportions
    example

**Comment by lslachciak** [comment]
basic list only

**Comment by lslachciak** [comment]
header color needs update
check proportions
example

**Comment by korneliakobiela** [comment]
I've checked the list element according to the HTML guide. It looks pretty the same as it looked in the previous version. All elements have the same colors and proportions. Tommorow morning I will edit example

**Comment by korneliakobiela** [comment]
PR is ready for this issue: #858

**Comment by lslachciak** [comment]
I have two remarks regarding this item
1. Font size of currently selected list item according to guide is 38px. Debugger shows me 36px
I think we should update font-size.
2. Content of example should be the same as is in guide. We plan in future do px to px comparison.
Basic List --> Title
List 01
List 02
...

**Comment by grzegorz-czajkowski** [comment]
@korneliakobiela and @lslachciak 
This issue seems to be done. Can we close this issue?

**Comment by lslachciak** [comment]
right
