### ISSUE TITLE
Controllers -> Master on/off switch

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#736]
Controllers -> Master on/off switch

@to do:
- integration on/off switch with listview
- ripple effect

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged. I think that the issue can be close.

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
I forget about ripple effect :(

**Comment by lslachciak** [comment]
i created new issue for ripple https://github.com/Samsung/TAU/issues/795

**Comment by lslachciak** [comment]
works fine
