### ISSUE TITLE
Controllers -> On/Off switch

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#737]

**Comment by lslachciak** [comment]
Controllers -> On/Off switch

**Comment by TomaszLukawskiSam** [comment]
I verified colors and sizes. In my opinion all is correct. I made little fix for example in UIComponents.

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged.

**Comment by lslachciak** [comment]
example should be updated when master switch on/off is done
(example in guideline contains master switch too)

**Comment by lslachciak** [comment]
works well, thank you
