### ISSUE TITLE
Buttons -> Contained Button -> List Area

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#739]
Buttons -> Contained Button -> List Area

**Comment by TomaszLukawskiSam** [comment]
Patch is already merged. The issue can be close.

**Comment by lslachciak** [comment]
@TomaszLukawskiSam 
I think we are too deep in example
See 
Contained Button->List Area -->Contained Button-->example
shouldn't it be 
Contained Button->List Area -->example?

**Comment by TomaszLukawskiSam** [comment]
Patches have already been merged. Can we close the issue?

**Comment by lslachciak** [comment]
@TomaszLukawskiSam I have one doubt here.
Font weight on buttons is bold. When looking on GUI Guide screenshots it seems more like normal not bold.
Is this because of global Roboto Medium definition Font Style as Bold (as in GUI font table)?

**Comment by TomaszLukawskiSam** [comment]
:( yes.
![image](https://user-images.githubusercontent.com/29534410/77403975-528f8d80-6db1-11ea-9fec-a737311afdcb.png)

This is problem with alternative font-style.

**Comment by lslachciak** [comment]
now font style was fixed. Closing
