### ISSUE TITLE
Buttons -> Contained Button -> Body Area

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#740]
Buttons -> Contained Button -> Body Area

**Comment by TomaszLukawskiSam** [comment]
Patch is already merged. The issue can be close.

**Comment by lslachciak** [comment]
Some remarks
1. Button example should be in Buttons section of UIComponents app not Controllers
2. Can we call example similar to guide i.e. Contained Button - Body Area
I mean
section Buttons -> Contained Button --> Body area
We try to keep structure similar to guide
3. Example texts doesn't correspond to guidelines texts
4. Do we cover here 2 buttons case? Should we create separate issue for this?

**Comment by lslachciak** [comment]
@TomaszLukawskiSam coul you check my remarks?

**Comment by TomaszLukawskiSam** [comment]
> @TomaszLukawskiSam coul you check my remarks?

Ok. I'll do changes.

**Comment by TomaszLukawskiSam** [comment]
I think that I did all required changes.

**Comment by lslachciak** [comment]
seems fine
