### ISSUE TITLE
Controllers -> Slider --> Continuous Slider

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#741]

**Comment by lslachciak** [comment]
Looks like after 849eefb542a0b8fe7ab2e25f8323886a58fa2624 Slider was broken

**Comment by TomaszLukawskiSam** [comment]
border-image: url(images/3_Controllers/tw_progress_bar_n.9.png) 5 fill;
    border-image-width: 3px;
    border-image-repeat: round;

**Comment by lslachciak** [comment]
Thank you @TomaszLukawskiSam I was trying this on Friday but without 
border-image-repeat: round;
option. I'll check.

**Comment by lslachciak** [comment]
Currently facing issue with setting opacity not for whole element but only border-image
CSS doesnt allow this directly
https://stackoverflow.com/questions/45085415/border-image-with-opacity
If I set opactiy for .ui-slider-bar it will also reflect .ui-slider-value

**Comment by lslachciak** [comment]
All current items completed. When new png/svg provided I'll update them
