### ISSUE TITLE
CSS px base change for tablet

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#745]
Set 
1dp:1.125 css pixel
for
Tablet 2560 * 1600 and 287 ppi

**Comment by TomaszLukawskiSam** [comment]
To solve this issue I want to do:
1. Change `@px_base` to `rem` units
2. Add `@media` query for tablet with `font-size` = 1.125 of default `font-size`

After this change all values in mobile TAU must are in `@px_base` - `px` unit will not allowed

**Comment by singa2000** [comment]
We don't need the change.
In the mobile, tablet are also 1sp=1dp=1px (css).
Sorry for confusion
