### ISSUE TITLE
Controllers -> Radio button --> radio animation

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#751]
Controllers -> Radio button --> radio animation

**Comment by singa2000** [comment]
When you implement the Radio animation,
please apply sprites animation sequentially using GUI resources.

![radio](https://user-images.githubusercontent.com/31196177/78327250-65773e80-75b7-11ea-8f22-0b19bbe17ba8.png)

**Comment by TomaszLukawskiSam** [comment]
> When you implement the Radio animation,
> please apply sprites animation sequentially using GUI resources.
> 
> ![radio](https://user-images.githubusercontent.com/31196177/78327250-65773e80-75b7-11ea-8f22-0b19bbe17ba8.png)


Your comment refers to Wearable GUI. This issue refers to mobile OneUI.

**Comment by TomaszLukawskiSam** [comment]
Patch (https://github.com/Samsung/TAU/pull/1044) has been already merged.

**Comment by lslachciak** [comment]
nice animation, thanks
