### ISSUE TITLE
Appbar --> Navigate up buttom -> no action

### ISSUE THREAD

**Issue by grzegorz-czajkowski** [Samsung/TAU#753]
User is not navigated backwards after click on back button in appbar examples.

Observations:
 * data-rel="back" is set
 * the proper behavior can be seen after replacing button element to link, for example <a href="" ...></a>
 * changes on router side are probably needed

**Comment by grzegorz-czajkowski** [comment]
Patch merged. Back button works. This change caused wrong width of ui-appbar-left-icons-container. Reported here https://github.com/Samsung/TAU/issues/764

**Comment by lslachciak** [comment]
thank you 
 works well
