### ISSUE TITLE
List -> Subheader

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#762]
![subb](https://user-images.githubusercontent.com/2246331/76765801-47c46f80-6797-11ea-835d-7ed69f460af1.png)
First Subheader in list example is cut

**Comment by lslachciak** [comment]
To discuss: should we have first subheader on list?
@HunseopJeong how do you think?

**Comment by lslachciak** [comment]
Also first subheader on list seems to be cut

**Comment by HunseopJeong** [comment]
@lslachciak 
Is it top position of the page?
I will check it.

**Comment by lslachciak** [comment]
Yes, exactly. You can see this issue in UIComponents app
But guide didn't say anything about header for first list on page

**Comment by HunseopJeong** [comment]
In my screen, it seems to be no problems. 
![image](https://user-images.githubusercontent.com/29908741/76835221-f6d57980-6871-11ea-8794-047928b66744.png)
Do you test the example in the emulator?

**Comment by HunseopJeong** [comment]
And you are right there is no guide about header for first list.

**Comment by lslachciak** [comment]
yes, the screen is from emulator,
[Version]
Model=Tizen5/Unified;
Build=tizen-unified_20191031.1;
Release=20191031.1;
[Build]
Type=eng;
Date=20191031_052150;
Time=05:21:50;
Variant=NONE;
ID=tizen-unified;

**Comment by HunseopJeong** [comment]
I removed subheader from the main page. So I close the issue.
