### ISSUE TITLE
Appbar --> Navigate up button -> wrong width of ui-appbar-left-icons-container

### ISSUE THREAD

**Issue by grzegorz-czajkowski** [Samsung/TAU#764]
After https://github.com/Samsung/TAU/pull/763, there is wrong width (8px) of ui-appbar-left-icons-container but it should have 32px. Only right margin (8px) of link element is taken into account.
It looks like icon size (24x24) is not properly added.

**Comment by lslachciak** [comment]
@TomaszLukawskiSam @grzegorz-czajkowski can we close this issue?

**Comment by grzegorz-czajkowski** [comment]
I will verify this.

**Comment by grzegorz-czajkowski** [comment]
Works fine. Thank you.
