### ISSUE TITLE
View controls ->  Dropdown list (Align_Top and Align_Bottom)

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#765]
View controls ->  Dropdown list

**Comment by lslachciak** [comment]
I afraid that we depend here on the AppBar -> "More option list" (or vice versa) https://github.com/Samsung/TAU/issues/715
@grzegorz-czajkowski how do you think?

**Comment by grzegorz-czajkowski** [comment]
Yes, Appbar needs dropdown list to implement "More options" menu.

**Comment by lslachciak** [comment]
@grzegorz-czajkowski when working on dropdown please note that resources are being updated.
Due to this there is an issue https://github.com/Samsung/TAU/issues/780

**Comment by grzegorz-czajkowski** [comment]
Align_Top and Align_Bottom guide pages were implemented by https://github.com/Samsung/TAU/pull/774.

**Comment by lslachciak** [comment]
works fine
