### ISSUE TITLE
App Bar -> Bottom bar (Text only)

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#769]

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged.

**Comment by lslachciak** [comment]
Height of the buttons on the bottom bar is 52. According to the guide it should be 56.
@TomaszLukawskiSam could you check?

**Comment by TomaszLukawskiSam** [comment]
You are right... I'll fix it.

**Comment by TomaszLukawskiSam** [comment]
Fixed. Could we close this issue?

**Comment by lslachciak** [comment]
yes, ready to go
