### ISSUE TITLE
View controls -> Dropdown list (Min width)

### ISSUE THREAD

**Issue by grzegorz-czajkowski** [Samsung/TAU#771]
Need to create a separate example and fix code/styles if needed.

**Comment by grzegorz-czajkowski** [comment]
Example + code fixes were merged. Issue can be closed.

**Comment by lslachciak** [comment]
As per other guide screens from AppBar examples menu should not be called Open but "Menu"
Please remember about this when working on other items.
Also Dropown list should have ripple effect (not high priority now)
https://github.com/Samsung/TAU/issues/832

**Comment by grzegorz-czajkowski** [comment]
`As per other guide screens from AppBar examples menu should not be called Open but "Menu"
Please remember about this when working on other items.`
In my opinion, "Menu" should be added to Appbar examples not to Dropdown examples (View controls -> Dropdown) since here they are not visible in guide.

```
Also Dropown list should have ripple effect (not high priority now)
#832
```
Ok, thanks.
