### ISSUE TITLE
View controls -> Dropdown list (Max width & height)

### ISSUE THREAD

**Issue by grzegorz-czajkowski** [Samsung/TAU#773]
Need to create a separate example and fix code/styles if needed.
Make sure that correct offset is applied after text: 16 px + 20 px + 24 px.

**Comment by grzegorz-czajkowski** [comment]
Example and implementation provided.

**Comment by lslachciak** [comment]
One issue reported https://github.com/Samsung/TAU/issues/845
but generall wors fine
