### ISSUE TITLE
Listview - dont'use tw_dropdown_ic_check.svg

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#779]
src/css/profile/mobile/common/dropdownmenu.less:				mask-image: url('images/13_View_Controls/tw_dropdown_ic_check.svg');

This file is not in current set of resources

**Comment by lslachciak** [comment]
@HunseopJeong please be aware about this issue

**Comment by HunseopJeong** [comment]
> @HunseopJeong please be aware about this issue

I got it.

**Comment by lslachciak** [comment]
this file was restored in d64ab2d7bff91f14c329f53c45c8499a32d40c90
