### ISSUE TITLE
Dropdown - dont use tw_dropdown_ic_check.svg

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#780]
src/css/profile/mobile/common/dropdownmenu.less:				mask-image: url('images/13_View_Controls/tw_dropdown_ic_check.svg');

This file is not in current resources set

**Comment by lslachciak** [comment]
@grzegorz-czajkowski please be aware about this issue

**Comment by grzegorz-czajkowski** [comment]
Ok, I will fix this,

**Comment by lslachciak** [comment]
thx

**Comment by grzegorz-czajkowski** [comment]
It looks like this file is missing from latest assets.
Latest guide still refers to tw_dropdown_ic_check.svg file but latest assets do not have this file.
W can neither temporarily restore this file from tree or wait for next guide/assets update.

**Comment by lslachciak** [comment]
@singa2000 could you check this with UX team?
@grzegorz-czajkowski I think that until further information is provided you can restore file

**Comment by grzegorz-czajkowski** [comment]
Patch merged.

**Comment by lslachciak** [comment]
@singa2000 we have implemented temporary solution (restored file) but please check with UX team why we are missing tw_dropdown_ic_check.svg
