### ISSUE TITLE
Listview - Examples are need to be rearranged 

### ISSUE THREAD

**Issue by HunseopJeong** [Samsung/TAU#782]
There are many examples for the list, but there are many duplicates, so it seems necessary to organize them.

Current Index for the list
**Stacked List**
- Basic List
- List Styles
- Reorder List
- Normal List
- Selectable List
- Expandable
- Expandable from JS
- List with On-Off elements
- Virtual List

**Grid View**
- Grid View
- Grid View with Label (outside)
- Grid View with Label (inside)
- Grid View with Checkbox
- Grid View with Badge
- Grid View with Move
- Grid View within Popup

**Comment by HunseopJeong** [comment]
I think we can remove the List Styles, and Normal List or combine two into own.
@lslachciak, @TomaszLukawskiSam,
How about your opinion?
If there's more to be removed, you can tell me.

**Comment by lslachciak** [comment]
Personally I would prefer to follow guideline and have just submenus like:
- List Width
- List contents area
- End of list
- Basic list
- Icon + text
- Subheader
- Expandalble list
- multiple selection

So according to your list I would leave only 
- Basic List
- Selection List
- Expandable List
And move rest somewhere to backup
The other list examples according to GUI will need to be provided in future.

**Comment by TomaszLukawskiSam** [comment]
I think we don't need backup. We have repository and complete version of UIComponents on branch 1.1

**Comment by HunseopJeong** [comment]
I reogranize the list example following structrue.
- List Width
- List Content Area
- End of list
-- Bottom spacing
-- Bottom spacing with FAB
- Basic List
- Icon + Text List
- Subheader
-- Subheader (Text)
-- Subheader (No text)
-- Subheader (Without chunking)
- Expandable List
- Multiple Selection List

**Comment by lslachciak** [comment]
Good idea

**Comment by HunseopJeong** [comment]
PR merged
