### ISSUE TITLE
Controllers -> Checkbox (animation)

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#785]
Checkbox should change state with animation.
- 26 keyframes
- images for animation are stored: images/3_Controllers/Checkbox/sem_checkedtextview_check_to_on_mtrl_026.svg
- lack of animation parameters like duration

**Comment by singa2000** [comment]
When you implement the checkbox animation, 
please apply sprites animation sequentially using GUI resources.

![checkbox](https://user-images.githubusercontent.com/31196177/78327129-1cbf8580-75b7-11ea-94b6-07a4cfba746f.png)

**Comment by TomaszLukawskiSam** [comment]
> When you implement the checkbox animation,
> please apply sprites animation sequentially using GUI resources.
> 
> ![checkbox](https://user-images.githubusercontent.com/31196177/78327129-1cbf8580-75b7-11ea-94b6-07a4cfba746f.png)

Your comment refers to Wearable GUI. This issue refers to mobile OneUI.

**Comment by TomaszLukawskiSam** [comment]
Patch has already been merged.
