### ISSUE TITLE
File naming rules in UI Components app

### ISSUE THREAD

**Issue by HunseopJeong** [Samsung/TAU#802]
In UI components app, various naming rules are applied.
Ex) In appbar, used the camel case "actionButton"
      In controlls, used the kebab case "checkbox-image-thumbnail.html"
      In graphs, used the snake case "bar_graph.html"
I think we need to unify in one way.
How about your opinions?
Which is best?

**Comment by TomaszLukawskiSam** [comment]
In my opinion, most are in format "kebab". I prefer this rule.
`checkbox-image-thumbnail.html`

**Comment by HunseopJeong** [comment]
Any other opinions? If not, I will create the PR to unify it with kebab case?
After that PR, please follow the rule.

**Comment by HunseopJeong** [comment]
@lslachciak, @singa2000, @DohyungLim 
Any other opinions?

**Comment by singa2000** [comment]
I also prefer to kebab.
It seems that Vue and Angular follows kebab like  https://angular.io/guide/styleguide.
It looks in general HTML use the kebab.

**Comment by HunseopJeong** [comment]
Okay. I will prepare the PR to apply kebab case.
I hope you will check this rule as you review.

**Comment by TomaszLukawskiSam** [comment]
@HunseopJeong 
Can we close the issue?

**Comment by HunseopJeong** [comment]
Issue was fixed.
