### ISSUE TITLE
View controls -> Dropdown list -> Two lines item

### ISSUE THREAD

**Issue by grzegorz-czajkowski** [Samsung/TAU#836]
Provide example and implementation in TAU.
See example in Appbar (Max-width)

**Comment by grzegorz-czajkowski** [comment]
There is discrepancy in guide related to dropdown max-width.

In 13-4 Dropdown list (Max width & height) on page 270 , long content is presented as follows:
`Option11 Option11 Option11 Option...`

one line only and dots are added to notify user that content has been shorten. This is already implemented by https://github.com/Samsung/TAU/pull/828.

However, in Appbar More optionlist (Max width) on page 51,  long content is presented as follows:
```
Lorem ipsum dolor sit amet, consectetur
adipiscing elit, sed do eiusmod tempor...
```
which means, content should be presented in maxium two lines and have a dots for longer text.

@singa2000  and @lslachciak the question is:
1) should we support one line item or
2) should we support two lines item or
3) both

**Comment by lslachciak** [comment]
@grzegorz-czajkowski I think both.
We have also two versions of Apbar - one line and two line

**Comment by grzegorz-czajkowski** [comment]
This feature requires -webkit-line-clamp css property which is not supported in Tizen Emulator 5.5:
![emulator](https://user-images.githubusercontent.com/46523330/77900303-27f47780-727e-11ea-86b6-8924456dc0aa.png)
whereas on Desktop using Chromium | 80.0.3987.87 (Official Build) Built on Ubuntu i looks like expected:
![Chromium](https://user-images.githubusercontent.com/46523330/77900422-4e1a1780-727e-11ea-9266-76ee2663c924.png)

Using line-height and max-heigh = 2 * line-height causes bottom-padding overflow. In addition, we would add "..." if string is longer in js code.

I will try creating two spans within li element to just show example.

**Comment by grzegorz-czajkowski** [comment]
Patch merged. Issue can be closed.
