### ISSUE TITLE
Controller -> Master on/off switch mis-behavior

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU#839]
If all sub-switches are turned off, the master switch should also be turned off.
It's not working well right now.

![image](https://user-images.githubusercontent.com/31196177/77714969-b28a6c00-701d-11ea-8ad7-74a148099f7e.png)

**Comment by lslachciak** [comment]
@singa2000  when working on this feature we had some doubts and internal discussion about this screen.
but your interpretation seems to be right, we will work on it

**Comment by singa2000** [comment]
You can refer to it UI guide ver1.6  - 37page .

3.Do not allow to turn off all sub settings when master is on. Let something work when you turn on the master switch.
4.Do not use the master switch in situations where that is not possible.

In the case of On, more than one sub-item should be on 
 (All Off is not available.)

**Comment by lslachciak** [comment]
Yes, we seen this when working  on feature. But we treated this guides more like guide for web app developer.
Not sure yet if those restrictions should be implemented on the widget side or sample app side.

**Comment by lslachciak** [comment]
As we discussed first we need to respond on the question

turning on/off master switch should 
1) only enable/disable all sub settings switches
2) both turn on/off and enabledisable sub setting switches

**Comment by singa2000** [comment]
I checked the Master on/off switch behavior with UX team,
Basically, Master on/off switch is just enable/disable the sub settings items.
1) Master switch Off -> sub settings are disable.
2) Master switch On-> sub settings are enables.

The UI guide will be update.
The App developer can change like followings.
If Master switch is off,  the sub settings can be hide or sub settings can be off.

Now our implementation is good working, so we can be close the issue.

**Comment by lslachciak** [comment]
@singa2000 thank you for clarification.
Closing issue
