### ISSUE TITLE
View controls -> Dropdown list -> "selected" attribute points to next option

### ISSUE THREAD

**Issue by grzegorz-czajkowski** [Samsung/TAU#842]
Adding "selected" attribute to <option> results in adding selection to next option.

**Comment by lslachciak** [comment]
This issue is because in html example "open" is also select so selectedIndex returns higher value
 https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/selectedIndex

```
				<select data-native-menu="false">
					<option selected data-placeholder="true" value="first-line" data-hide-placeholder-menu-items="false">
						Open
					</option>
					<option value="1">
						Option1
					</option>
					<option value="2">
						Option2
					</option>
					<option value="3">
						Option3
					</option>
					<option value="4">
						Option4
					</option>
				</select>

```

**Comment by grzegorz-czajkowski** [comment]
Open is just placeholder and is not part of the list itself. Adding selected to this is confusing. But adding selected to Option1 results in showing selection for Option2.

**Comment by lslachciak** [comment]
PR is read for review, waiting for final approval

**Comment by lslachciak** [comment]
PR merged, approved
