### ISSUE TITLE
View Controls -> Drop down list --> Max width --> in the center of screen

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#845]
1 expand dropdown list
2. make a drag on the expanded list 
3. select an item
Observe: Drop down list is in the middle of screen

**Comment by TomaszLukawskiSam** [comment]
I think that the AppBar has been extended during the scroll of Drop Down menu.

**Comment by lslachciak** [comment]
yes, this is true.
extension of AppBar occurs always. Not sure if this is correct behaviour.
But regardless of this drags on the expandable list should not cause such behaviour

**Comment by TomaszLukawskiSam** [comment]
Of course this is not correct behaviour. The extension of AppBar should be block when dialog / poup is visible.

**Comment by lslachciak** [comment]
on console there is a message
`Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`

**Comment by lslachciak** [comment]
Related links
https://developers.google.com/web/updates/2017/01/scrolling-intervention
 https://github.com/inuyaksa/jquery.nicescroll/issues/799

**Comment by lslachciak** [comment]
issue also occurs on emulator
![image](https://user-images.githubusercontent.com/2246331/77895806-997cf780-7277-11ea-8981-ced858633f29.png)

**Comment by lslachciak** [comment]
console error can be eliminated with this patch
```
diff --git a/src/js/core/event/gesture/Manager.js b/src/js/core/event/gesture/Manager.js
index 8ad3881..d36a5b0 100644
--- a/src/js/core/event/gesture/Manager.js
+++ b/src/js/core/event/gesture/Manager.js
@@ -104,7 +104,7 @@
                                        var self = this;
 
                                        if (self.touchSupport) {
-                                               document.addEventListener("touchmove", self);
+                                               document.addEventListener("touchmove", self, {passive: false});
                                                document.addEventListener("touchend", self);
                                                document.addEventListener("touchcancel", self);

```
but this not eliminates issue yet

**Comment by lslachciak** [comment]
PR merged
