### ISSUE TITLE
Controllers -> Checkbox --> animation

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#849]

**Comment by TomaszLukawskiSam** [comment]
I have already done some work in the context of this PR.

https://github.com/TomaszLukawskiSam/TAU/commit/0c196774474cb8307bc4c88383662ab0b22399bb

Please check less file: src/css/profile/mobile/common/gridview.less

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
Which profile did you have on mind? Milestone shows mobile.

**Comment by TomaszLukawskiSam** [comment]
Patch has been already merged.

**Comment by lslachciak** [comment]
nice checkbox animation
