### ISSUE TITLE
Spin widget tests

### ISSUE THREAD

**Issue by HunseopJeong** [Samsung/TAU#855]
I am stuck in the test for the Spin.
I moved the Spin widget of wearable profile to the core widget.
But [CI](https://travis-ci.org/github/Samsung/TAU/builds/668705271?utm_medium=notification&utm_source=github_status) makes fail reports  repeatedly.

Is there any widget like as Spin, define the core part in core widget and extend it for the profiles?

**Comment by HunseopJeong** [comment]
@TomaszLukawskiSam,
 Is there a widget that acts like Spin? Do you know?

**Comment by HunseopJeong** [comment]
I tried to make the 'tests/js/core/widget/core/Spin' first.
But it gots correct result only in wearable and not in mobile.

**Comment by TomaszLukawskiSam** [comment]
I think we don't have widget similar to Spin... I'll check your PR (#820) but I see that tests passed.

**Comment by HunseopJeong** [comment]
Okay, I fixed isssue but I think need a more time to analyze it :(

**Comment by TomaszLukawskiSam** [comment]
@HunseopJeong 
Hi, I added commit (https://github.com/Samsung/TAU/pull/820/commits/7ff86754dd46c94cb3097129f50af7e162b2ad64) to your PR (#820).

**Comment by HunseopJeong** [comment]
@TomaszLukawskiSam,
Could you make the PR([7ff8675](https://github.com/Samsung/TAU/commit/7ff86754dd46c94cb3097129f50af7e162b2ad64)) after #820?

**Comment by TomaszLukawskiSam** [comment]
> @TomaszLukawskiSam,
> Could you make the PR([7ff8675](https://github.com/Samsung/TAU/commit/7ff86754dd46c94cb3097129f50af7e162b2ad64)) after #820?

Done.

**Comment by TomaszLukawskiSam** [comment]
The PR is ready for review. Can I assign you to review?

**Comment by HunseopJeong** [comment]
@TomaszLukawskiSam,
Thank you,
After merging the #820, I will review it!
Please assign me.

**Comment by TomaszLukawskiSam** [comment]
Great :) Thanks.

**Comment by HunseopJeong** [comment]
PR merged
