### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive......

### ISSUE THREAD

**Issue by HunseopJeong** [Samsung/TAU#867]
When I tried to test the example on the browesr, some error message appeared on the console window.
```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. ....
```

**Comment by lslachciak** [comment]
@HunseopJeong I think this is duplicate of
https://github.com/Samsung/TAU/issues/859
Working on PR to fix this issue
https://github.com/Samsung/TAU/pull/860

**Comment by HunseopJeong** [comment]
Oh,, Good jobs :D
I close issue.
