### ISSUE TITLE
Progress --> Progress Bar (Determinate)

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#875]

**Comment by korneliakobiela** [comment]
I checked the current state of this with the example, and it looks nearly identical for basic Progress Bar. @lslachciak is this task about all types of progress bar (with and without texts) or only basic type?

**Comment by korneliakobiela** [comment]
I've edited JS files today. But there is some build issue. I am trying to solve it.

**Comment by korneliakobiela** [comment]
All changes are merged. I made UX issue for this : #1037.

**Comment by lslachciak** [comment]
@korneliakobiela Progress bar examples should be located in Progress Menu
could you made also PR moving them to appropriate position?

**Comment by lslachciak** [comment]
I updated title of this issue according tot he v.1.9 of guide

**Comment by lslachciak** [comment]
OK, according to 1.9 guide.
But for 2.0 guide we will need to have new issue
