### ISSUE TITLE
Text fields -> Text Fields

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#877]

**Comment by lslachciak** [comment]
Text fields only (Labels handled separately)

**Comment by lslachciak** [comment]
some fixes are needed
![image](https://user-images.githubusercontent.com/2246331/78135231-db49a180-7421-11ea-8289-ac08a4c970e6.png)

**Comment by lslachciak** [comment]
After some fixes looks much better now
![image](https://user-images.githubusercontent.com/2246331/78140147-d4269180-7429-11ea-9112-12ef7ec1e6b4.png)
but need to clarify "Hint text Inactive" vs "Hint text activated" from guide
Probably will need to add some JS to recognise focus state of input field and change placeholder value

**Comment by lslachciak** [comment]
PR merged
