### ISSUE TITLE
Listview with subtext 3 lines: next item doesn't show

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#88]
![image](https://user-images.githubusercontent.com/29534410/57609485-46bb2400-756f-11e9-89ec-a1bdea09c1e5.png)

Some previous patch for listview broken the widget look.

Example:
examples/wearable/UIComponents/contents/list/subtext/list_subtext_3line.html

Example of proper view:
![image](https://user-images.githubusercontent.com/29534410/57611162-83d4e580-7572-11e9-8040-6568beb33df1.png)

**Comment by lslachciak** [comment]
@pkaczmarczy can we close issue?

**Comment by pkaczmarczy** [comment]
Yes, I will close issue. The https://github.com/Samsung/TAU/pull/99 has been merged.
