### ISSUE TITLE
Cotrollers --> Checkbox (List selected) -->Bottom bar --> Move icon is wrong

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#884]
Cotrollers --> Checkbox (List selected) -->Bottom bar --> Move icon is wrong
![image](https://user-images.githubusercontent.com/2246331/78215934-0a5f2200-74b9-11ea-87a5-73ab90192173.png)

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
Duplicate issue https://github.com/Samsung/TAU/issues/846

**Comment by lslachciak** [comment]
@singa2000 could you contact with UX so we can get proper icon for Move
we have other icons in src/css/profile/mobile/theme-changeable/images/1_App_Bar/
but not move icon

**Comment by singa2000** [comment]
It fixed and merged
