### ISSUE TITLE
Controllers -> On/Off switch

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU#889]
1. Switch_Tap
   When just  Tap event, apply the elastic
    false→true
    elastic_60 + duration (500 ms)
    true→false
    elastic_60 + duration (500 ms)

2. Switch_Drag
   When just Drag event, don't apply the elastic
   Up event :  SineInOut60 + duration (200 ms)
   When drag, the background color changes in real time so that it is reflected.

**Comment by TomaszLukawskiSam** [comment]
@singa2000 @lslachciak 
Hi,
I need help with found definition for "elastic_60"
I can define this by by cubic-bezier eg. (https://cubic-bezier.com/#.6,.6,.8,1.49)

The SineInOut60 also needs definition.

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
I'm not sure what is the definition `elastic_60` and `SineInOut60`

**Comment by lslachciak** [comment]
@singa2000  by sineInOut do you mean Sine_EasyIn/Out as defined on p.8 in [OneUI_Watch2.X]Basic_Interaction_VI.pptx (for wearable)?

**Comment by TomaszLukawskiSam** [comment]
I'll start implement the drag feature. The timing function can be implemented next time.

**Comment by lslachciak** [comment]
We discussed with TOmasz that until clarification of
elastic_60 and SineInOut60 Tomasz will concentrate on drag support in this issue.

**Comment by lslachciak** [comment]
@TomaszLukawskiSam was the drag support added?

**Comment by TomaszLukawskiSam** [comment]
Drag support has been implemented,
but this issue describes also other issues.

**Comment by lslachciak** [comment]
Drag support was implemented
@singa2000 how about closing this issue - drag support was implemented and opening new one when elastic_60 and SineInOut60 is clarified?

**Comment by lslachciak** [comment]
closing - drag support was implemented for milestone M_PH3
please feel free to open seprate issue with details for elastic_60 and SineInOut60 issue
