### ISSUE TITLE
Controllers -> SLider (update for 1.9)

### ISSUE THREAD

**Issue by lmslachciak** [Samsung/TAU#893]
Controllers -> Slider (update for 1.9)

**Comment by TomaszLukawskiSam** [comment]
@lslachciak 
I found one issue in slider referring to 1.8 guideline. This is focus issue:
![obraz](https://user-images.githubusercontent.com/29534410/80938960-4a2c6880-8ddb-11ea-828e-a66883ac43a8.png)

**Comment by lslachciak** [comment]
Yes, you are right

**Comment by TomaszLukawskiSam** [comment]
We can close the issue.
