### ISSUE TITLE
Presentation views -> List -> Main Text Only -> ui-arc-listview-5 items have wrong size

### ISSUE THREAD

**Issue by grzegorz-czajkowski** [Samsung/TAU#905]
Items arround selected elements have wrong position, size and opacity.
Current state:
![Screenshot from 2020-04-06 14-14-15](https://user-images.githubusercontent.com/46523330/78634461-525cbb00-78a4-11ea-851e-ece4e2f32af1.png)

**Comment by lslachciak** [comment]
Debugger shows me 36px guide shows 38 px for main item font size (List 03)

**Comment by grzegorz-czajkowski** [comment]
font-size is already updated in https://github.com/Samsung/TAU/pull/887. I can see correct font size = 38px.
