### ISSUE TITLE
Listview: grey area is shown

### ISSUE THREAD

**Issue by TomaszLukawskiSam** [Samsung/TAU#94]
Implements two colored listview widgets on the same page is not supported yet.
 
The guideline for Tizen 3.0 doesn't provide use case with many colored listview in the same time on the same page.
Resolve the issue requires synchronization between lists.

Second issue is when developer does listview update by innerHtml property. In this way he destroys instance of canvas with colored bars.

**Comment by lslachciak** [comment]
@TomaszLukawskiSam PR merged, how about closing this issue?

**Comment by TomaszLukawskiSam** [comment]
Yes. Patch have been already merged.
