### ISSUE TITLE
Wearable Selector bug

### ISSUE THREAD

**Issue by DevronB** [Samsung/TAU#958]
In there wearable selector widget control, if you have 1 item more than a full page (12 as full page is 11) and you navigate to the next layer with '>>' the widget navigation and animations break and you can't go back to the previous layer. It works fine with <12 and >12, but not exactly 12 items.

**Comment by HunseopJeong** [comment]
Hello, @DevronB,
Which version of TAU are you using?
I tested selector(Controls-Selector-BasicSelector) with 12 items(TAU 1.1.11).
There was no issue.
I will help you if you provide details of the environment you are testing.

**Comment by DevronB** [comment]
I'm using TAU 1.0 It only occurs if you have 1 item on the second layer. So you press the >> at the top and it spins to the second layer. If there's only one item there it then breaks navigation.

**Comment by HunseopJeong** [comment]
@DevronB, Sorry for the late answer.
I tested it as you said in version 1.0.27, but it doesn't seem to cause any problems. 
How about updating to the latest version?
![image](https://user-images.githubusercontent.com/29908741/83253947-d702f000-a1e8-11ea-878a-8b36f9928437.png)

**Comment by DevronB** [comment]
Hi @HunseopJeong, I am using 1.0.27. In your tests above can you then navigate back to the previous layer by bezel and screen tap? this is where mine breaks navigation?

**Comment by HunseopJeong** [comment]
![image](https://user-images.githubusercontent.com/29908741/83391491-82e94d00-a42e-11ea-906f-6542cab2e984.png)
@DevronB , Yes I can navigate to the previous layer by screen tap.
