### ISSUE TITLE
TypeScript type definitions for TAU

### ISSUE THREAD

**Issue by nemethmik** [Samsung/TAU#970]
Hello TAU Developer Friends,
I have started experimenting with TAU for a watch-friendly mobile business application and so far it seems to be ok for our requirements. I didn't find either @types/tau or @types/tizen.
Do you have type definitions for TAU?
Thank you so much,
Miklos from Budapest

**Comment by HunseopJeong** [comment]
Hello, @nemethmik,
We do not yet have @types for typescript support.
We will consider whether we can support related features.

@lslachciak, @singa2000 
Could you check this issue?

**Comment by singa2000** [comment]
Hello.@nemethmik
Thank you very much for your interest in TAU.
I'm sorry but we don't yet support typescript and can't be sure of supporting it right now.
We will consider it as one of the next item.

**Comment by nemethmik** [comment]
It's OK. I wanted to know if you already have types on your roadmap. Thank you so much.
