### ISSUE TITLE
TAU 1.1.8 (Tizen Studio 3.7) doesn't support number input fields

### ISSUE THREAD

**Issue by nemethmik** [Samsung/TAU#971]
Hello,
In the video I created the TAU UI Components sample project with Tizen Studio, and when I wanted to change the **input type** to **number** the application was broken.
[TAU 1.1.8 (Tizen Studio 3.7) doesn't support number input fields](https://youtu.be/a8TlFG23rkY)
In our application we have a number of simple screens with number input fields.
Thank you so much,
Miklos

**Comment by HunseopJeong** [comment]
Hello, @nemethmik,
It was easy to understand that checked the issue with a video.
I will check the issue.

**Comment by HunseopJeong** [comment]
@lslachciak,
Could you merge this PR(https://github.com/Samsung/TAU/pull/978) to all branches in next release?

**Comment by lslachciak** [comment]
> 
> 
> @lslachciak,
> Could you merge this PR(#978) to all branches in next release?

Yes, I'm on it. 1.1 is done. 1.2 is in progress

**Comment by lslachciak** [comment]
PR was merged to all branches

**Comment by lslachciak** [comment]
@nemethmik appropriate changes were introduced into TAU 1.0, 1.1 and 1.2 and released 
https://github.com/Samsung/TAU/releases/tag/v.1.2.1
although process of incorporating changes into Tizen Studio can take some time (tests, etc..) and is out of scope of TAU issue

If you want I can prepare special release of TAU 1.1 too which has this change
