### ISSUE TITLE
TAU 1.1.8 (Tizen Studio 3.7) Toggle looks weird on regular page without a UL-tag list view

### ISSUE THREAD

**Issue by nemethmik** [Samsung/TAU#972]
Hi,
Here I used the TAU UI sample project to show how the toggle TAU element is rendered on a regular page. It looks fine when included in a proper LI element of a UL list view, but not anywhere else.
[TAU 1.1.8 (Tizen Studio 3.7) Toggle looks weird on regular page without a UL-tag list view](https://youtu.be/6lmWVagpoa4)
Thank you and all the best,
Miklos

**Comment by HunseopJeong** [comment]
Hello @nemethmik,
Sorry for late answer. You are right. 
Currently, many components are designed based on the li element.
Because wearable profile is based on a list.
Therefore, I recommended to create an app based on a list.
