### ISSUE TITLE
No TAU templates in the new Tizen Studio 3.7

### ISSUE THREAD

**Issue by nemethmik** [Samsung/TAU#982]
Tizen Studio 3.7 was released earlier this month (April 2020) and when you want to create a new Tizen Wearable or Mobile web app project you have no TAU templates any more. Have you noticed this, My Friends? The TAU UI sample project is still available but no TAU templates, just the basic templates. 
Take care and all the best, Miklos

**Comment by singa2000** [comment]
Hello @nemethmik 
I checked the Tizen Studio 3.7 and can see the Mobile/Wearable TAU Template.
After install the Tizen Studio 3.7, do you run the package-manager?
If not, would you install the Mobile or Wearable project in the package-manager, please?

![package-manager](https://user-images.githubusercontent.com/31196177/79954211-facf6980-84b7-11ea-96b5-d82e8d2923dc.png)

After install it in the package-manager, you still can't find the TAU Template, would you tell me again, please?

Thanks for your reporting the issue.

**Comment by nemethmik** [comment]
Yes, it's there. Brilliant.
I am really sorry for the turbulence.
Thank you so much.
