### ISSUE TITLE
Mobile Appbar action button issue

### ISSUE THREAD

**Issue by singa2000** [Samsung/TAU#998]
I test latest PR, the App bar is abnormal.
Navigate up button and action button are not display.

First the flat button icon of Appbar is not visible. But when I select the button, the icon is visible.

How to reproduce:
App bar -> Action button -> Add and Search 

Test version:
commit 0a6c08e824f575d1dc33fc458d77fea423f0715c (HEAD -> feedback9, upstream/tau_1.2, tau_1.2)
Author: Hunseop Jeong <hs85.jeong@samsung.com>
Date:   Wed Apr 22 08:10:04 2020 +0900
    List (mobile): Fix to apply GUI feedback

**Comment by TomaszLukawskiSam** [comment]
An indirect reason for this error is the lack of background color for the element `:after` for flat button.
![obraz](https://user-images.githubusercontent.com/29534410/80181336-efd61f80-8604-11ea-8532-22a22222bd38.png)
I try to find change which broke this color.

**Comment by TomaszLukawskiSam** [comment]
This change (0a6c08e824f575d1dc33fc458d77fea423f0715c) broken background color for button.

**Comment by TomaszLukawskiSam** [comment]
I'm preparing patch for this issue, now.

**Comment by HunseopJeong** [comment]
I removed the style  because it makes some issues on the fab button.
I will check it.

**Comment by lslachciak** [comment]
@singa2000 I think we can close this issue PR merged
